/* tslint:disable */
/* eslint-disable */
/**
 * TeamUp API
 * Sports venue booking and team formation API  Features: - Venue search with geolocation - Timeslot booking - TeamUp creation and management - Join request workflow 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { OwnerOut } from './OwnerOut';
import {
    OwnerOutFromJSON,
    OwnerOutFromJSONTyped,
    OwnerOutToJSON,
    OwnerOutToJSONTyped,
} from './OwnerOut';
import type { EventParticipantOut } from './EventParticipantOut';
import {
    EventParticipantOutFromJSON,
    EventParticipantOutFromJSONTyped,
    EventParticipantOutToJSON,
    EventParticipantOutToJSONTyped,
} from './EventParticipantOut';
import type { EventBookingDetail } from './EventBookingDetail';
import {
    EventBookingDetailFromJSON,
    EventBookingDetailFromJSONTyped,
    EventBookingDetailToJSON,
    EventBookingDetailToJSONTyped,
} from './EventBookingDetail';

/**
 * 
 * @export
 * @interface EventOut
 */
export interface EventOut {
    /**
     * 
     * @type {string}
     * @memberof EventOut
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof EventOut
     */
    title: string;
    /**
     * URL or path to event image
     * @type {string}
     * @memberof EventOut
     */
    image?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EventOut
     */
    description?: string | null;
    /**
     * 
     * @type {EventOutStatusEnum}
     * @memberof EventOut
     */
    status: EventOutStatusEnum;
    /**
     * 
     * @type {number}
     * @memberof EventOut
     */
    maxParticipants: number;
    /**
     * 
     * @type {number}
     * @memberof EventOut
     */
    currentParticipants: number;
    /**
     * 
     * @type {OwnerOut}
     * @memberof EventOut
     */
    owner?: OwnerOut;
    /**
     * 
     * @type {EventOutVisibilityEnum}
     * @memberof EventOut
     */
    visibility: EventOutVisibilityEnum;
    /**
     * 
     * @type {EventOutDurationTypeEnum}
     * @memberof EventOut
     */
    durationType: EventOutDurationTypeEnum;
    /**
     * 
     * @type {Date}
     * @memberof EventOut
     */
    createdAt: Date;
    /**
     * 
     * @type {Array<EventParticipantOut>}
     * @memberof EventOut
     */
    participants?: Array<EventParticipantOut> | null;
    /**
     * 
     * @type {Array<EventBookingDetail>}
     * @memberof EventOut
     */
    bookings?: Array<EventBookingDetail> | null;
    /**
     * 
     * @type {EventOutUserJoinStatusEnum}
     * @memberof EventOut
     */
    userJoinStatus?: EventOutUserJoinStatusEnum;
}


/**
 * @export
 */
export const EventOutStatusEnum = {
    Open: 'open',
    Closed: 'closed'
} as const;
export type EventOutStatusEnum = typeof EventOutStatusEnum[keyof typeof EventOutStatusEnum];

/**
 * @export
 */
export const EventOutVisibilityEnum = {
    Public: 'public',
    Private: 'private'
} as const;
export type EventOutVisibilityEnum = typeof EventOutVisibilityEnum[keyof typeof EventOutVisibilityEnum];

/**
 * @export
 */
export const EventOutDurationTypeEnum = {
    Temporary: 'temporary',
    Permanent: 'permanent'
} as const;
export type EventOutDurationTypeEnum = typeof EventOutDurationTypeEnum[keyof typeof EventOutDurationTypeEnum];

/**
 * @export
 */
export const EventOutUserJoinStatusEnum = {
    None: 'none',
    Pending: 'pending',
    Joined: 'joined'
} as const;
export type EventOutUserJoinStatusEnum = typeof EventOutUserJoinStatusEnum[keyof typeof EventOutUserJoinStatusEnum];


/**
 * Check if a given object implements the EventOut interface.
 */
export function instanceOfEventOut(value: object): value is EventOut {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('maxParticipants' in value) || value['maxParticipants'] === undefined) return false;
    if (!('currentParticipants' in value) || value['currentParticipants'] === undefined) return false;
    if (!('visibility' in value) || value['visibility'] === undefined) return false;
    if (!('durationType' in value) || value['durationType'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function EventOutFromJSON(json: any): EventOut {
    return EventOutFromJSONTyped(json, false);
}

export function EventOutFromJSONTyped(json: any, ignoreDiscriminator: boolean): EventOut {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'title': json['title'],
        'image': json['image'] == null ? undefined : json['image'],
        'description': json['description'] == null ? undefined : json['description'],
        'status': json['status'],
        'maxParticipants': json['max_participants'],
        'currentParticipants': json['current_participants'],
        'owner': json['owner'] == null ? undefined : OwnerOutFromJSON(json['owner']),
        'visibility': json['visibility'],
        'durationType': json['duration_type'],
        'createdAt': (new Date(json['created_at'])),
        'participants': json['participants'] == null ? undefined : ((json['participants'] as Array<any>).map(EventParticipantOutFromJSON)),
        'bookings': json['bookings'] == null ? undefined : ((json['bookings'] as Array<any>).map(EventBookingDetailFromJSON)),
        'userJoinStatus': json['user_join_status'] == null ? undefined : json['user_join_status'],
    };
}

export function EventOutToJSON(json: any): EventOut {
    return EventOutToJSONTyped(json, false);
}

export function EventOutToJSONTyped(value?: EventOut | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'title': value['title'],
        'image': value['image'],
        'description': value['description'],
        'status': value['status'],
        'max_participants': value['maxParticipants'],
        'current_participants': value['currentParticipants'],
        'owner': OwnerOutToJSON(value['owner']),
        'visibility': value['visibility'],
        'duration_type': value['durationType'],
        'created_at': value['createdAt'].toISOString(),
        'participants': value['participants'] == null ? undefined : ((value['participants'] as Array<any>).map(EventParticipantOutToJSON)),
        'bookings': value['bookings'] == null ? undefined : ((value['bookings'] as Array<any>).map(EventBookingDetailToJSON)),
        'user_join_status': value['userJoinStatus'],
    };
}

