/* tslint:disable */
/* eslint-disable */
/**
 * TeamUp API
 * Sports venue booking and team formation API  Features: - Venue search with geolocation - Timeslot booking - TeamUp creation and management - Join request workflow 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface HealthCheck200Response
 */
export interface HealthCheck200Response {
    /**
     * 
     * @type {string}
     * @memberof HealthCheck200Response
     */
    status: string;
}

/**
 * Check if a given object implements the HealthCheck200Response interface.
 */
export function instanceOfHealthCheck200Response(value: object): value is HealthCheck200Response {
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function HealthCheck200ResponseFromJSON(json: any): HealthCheck200Response {
    return HealthCheck200ResponseFromJSONTyped(json, false);
}

export function HealthCheck200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): HealthCheck200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
    };
}

export function HealthCheck200ResponseToJSON(json: any): HealthCheck200Response {
    return HealthCheck200ResponseToJSONTyped(json, false);
}

export function HealthCheck200ResponseToJSONTyped(value?: HealthCheck200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
    };
}

