/* tslint:disable */
/* eslint-disable */
/**
 * TeamUp API
 * Sports venue booking and team formation API  Features: - Venue search with geolocation - Timeslot booking - TeamUp creation and management - Join request workflow 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface JoinRequestReviewIn
 */
export interface JoinRequestReviewIn {
    /**
     * 
     * @type {JoinRequestReviewInActionEnum}
     * @memberof JoinRequestReviewIn
     */
    action: JoinRequestReviewInActionEnum;
}


/**
 * @export
 */
export const JoinRequestReviewInActionEnum = {
    Approve: 'approve',
    Reject: 'reject'
} as const;
export type JoinRequestReviewInActionEnum = typeof JoinRequestReviewInActionEnum[keyof typeof JoinRequestReviewInActionEnum];


/**
 * Check if a given object implements the JoinRequestReviewIn interface.
 */
export function instanceOfJoinRequestReviewIn(value: object): value is JoinRequestReviewIn {
    if (!('action' in value) || value['action'] === undefined) return false;
    return true;
}

export function JoinRequestReviewInFromJSON(json: any): JoinRequestReviewIn {
    return JoinRequestReviewInFromJSONTyped(json, false);
}

export function JoinRequestReviewInFromJSONTyped(json: any, ignoreDiscriminator: boolean): JoinRequestReviewIn {
    if (json == null) {
        return json;
    }
    return {
        
        'action': json['action'],
    };
}

export function JoinRequestReviewInToJSON(json: any): JoinRequestReviewIn {
    return JoinRequestReviewInToJSONTyped(json, false);
}

export function JoinRequestReviewInToJSONTyped(value?: JoinRequestReviewIn | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'action': value['action'],
    };
}

