/* tslint:disable */
/* eslint-disable */
/**
 * TeamUp API
 * Sports venue booking and team formation API  Features: - Venue search with geolocation - Timeslot booking - TeamUp creation and management - Join request workflow 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface JoinRequestReviewResponse
 */
export interface JoinRequestReviewResponse {
    /**
     * 
     * @type {boolean}
     * @memberof JoinRequestReviewResponse
     */
    ok: boolean;
    /**
     * 
     * @type {JoinRequestReviewResponseStatusEnum}
     * @memberof JoinRequestReviewResponse
     */
    status: JoinRequestReviewResponseStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof JoinRequestReviewResponse
     */
    message: string;
}


/**
 * @export
 */
export const JoinRequestReviewResponseStatusEnum = {
    Submitted: 'submitted',
    Approved: 'approved',
    Rejected: 'rejected'
} as const;
export type JoinRequestReviewResponseStatusEnum = typeof JoinRequestReviewResponseStatusEnum[keyof typeof JoinRequestReviewResponseStatusEnum];


/**
 * Check if a given object implements the JoinRequestReviewResponse interface.
 */
export function instanceOfJoinRequestReviewResponse(value: object): value is JoinRequestReviewResponse {
    if (!('ok' in value) || value['ok'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function JoinRequestReviewResponseFromJSON(json: any): JoinRequestReviewResponse {
    return JoinRequestReviewResponseFromJSONTyped(json, false);
}

export function JoinRequestReviewResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): JoinRequestReviewResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'ok': json['ok'],
        'status': json['status'],
        'message': json['message'],
    };
}

export function JoinRequestReviewResponseToJSON(json: any): JoinRequestReviewResponse {
    return JoinRequestReviewResponseToJSONTyped(json, false);
}

export function JoinRequestReviewResponseToJSONTyped(value?: JoinRequestReviewResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ok': value['ok'],
        'status': value['status'],
        'message': value['message'],
    };
}

