/* tslint:disable */
/* eslint-disable */
/**
 * TeamUp API
 * Sports venue booking and team formation API  Features: - Venue search with geolocation - Timeslot booking - TeamUp creation and management - Join request workflow 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TicketCreateIn
 */
export interface TicketCreateIn {
    /**
     * 
     * @type {Date}
     * @memberof TicketCreateIn
     */
    date: Date;
    /**
     * 
     * @type {string}
     * @memberof TicketCreateIn
     */
    startTime: string;
    /**
     * 
     * @type {number}
     * @memberof TicketCreateIn
     */
    durationMinutes: number;
    /**
     * 
     * @type {string}
     * @memberof TicketCreateIn
     */
    sportType: string;
    /**
     * 
     * @type {TicketCreateInIntensityEnum}
     * @memberof TicketCreateIn
     */
    intensity: TicketCreateInIntensityEnum;
    /**
     * At least one venue ID is required
     * @type {Array<string>}
     * @memberof TicketCreateIn
     */
    venueIds: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof TicketCreateIn
     */
    priceMin?: number | null;
    /**
     * 
     * @type {number}
     * @memberof TicketCreateIn
     */
    priceMax?: number | null;
    /**
     * 
     * @type {string}
     * @memberof TicketCreateIn
     */
    currency?: string;
}


/**
 * @export
 */
export const TicketCreateInIntensityEnum = {
    Low: 'Low',
    Medium: 'Medium',
    High: 'High'
} as const;
export type TicketCreateInIntensityEnum = typeof TicketCreateInIntensityEnum[keyof typeof TicketCreateInIntensityEnum];


/**
 * Check if a given object implements the TicketCreateIn interface.
 */
export function instanceOfTicketCreateIn(value: object): value is TicketCreateIn {
    if (!('date' in value) || value['date'] === undefined) return false;
    if (!('startTime' in value) || value['startTime'] === undefined) return false;
    if (!('durationMinutes' in value) || value['durationMinutes'] === undefined) return false;
    if (!('sportType' in value) || value['sportType'] === undefined) return false;
    if (!('intensity' in value) || value['intensity'] === undefined) return false;
    if (!('venueIds' in value) || value['venueIds'] === undefined) return false;
    return true;
}

export function TicketCreateInFromJSON(json: any): TicketCreateIn {
    return TicketCreateInFromJSONTyped(json, false);
}

export function TicketCreateInFromJSONTyped(json: any, ignoreDiscriminator: boolean): TicketCreateIn {
    if (json == null) {
        return json;
    }
    return {
        
        'date': (new Date(json['date'])),
        'startTime': json['start_time'],
        'durationMinutes': json['duration_minutes'],
        'sportType': json['sport_type'],
        'intensity': json['intensity'],
        'venueIds': json['venue_ids'],
        'priceMin': json['price_min'] == null ? undefined : json['price_min'],
        'priceMax': json['price_max'] == null ? undefined : json['price_max'],
        'currency': json['currency'] == null ? undefined : json['currency'],
    };
}

export function TicketCreateInToJSON(json: any): TicketCreateIn {
    return TicketCreateInToJSONTyped(json, false);
}

export function TicketCreateInToJSONTyped(value?: TicketCreateIn | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'date': value['date'].toISOString().substring(0,10),
        'start_time': value['startTime'],
        'duration_minutes': value['durationMinutes'],
        'sport_type': value['sportType'],
        'intensity': value['intensity'],
        'venue_ids': value['venueIds'],
        'price_min': value['priceMin'],
        'price_max': value['priceMax'],
        'currency': value['currency'],
    };
}

