/* tslint:disable */
/* eslint-disable */
/**
 * TeamUp API
 * Sports venue booking and team formation API  Features: - Venue search with geolocation - Timeslot booking - TeamUp creation and management - Join request workflow 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateUserInfoRequest
 */
export interface UpdateUserInfoRequest {
    /**
     * 
     * @type {string}
     * @memberof UpdateUserInfoRequest
     */
    displayName?: string;
}

/**
 * Check if a given object implements the UpdateUserInfoRequest interface.
 */
export function instanceOfUpdateUserInfoRequest(value: object): value is UpdateUserInfoRequest {
    return true;
}

export function UpdateUserInfoRequestFromJSON(json: any): UpdateUserInfoRequest {
    return UpdateUserInfoRequestFromJSONTyped(json, false);
}

export function UpdateUserInfoRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateUserInfoRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'displayName': json['display_name'] == null ? undefined : json['display_name'],
    };
}

export function UpdateUserInfoRequestToJSON(json: any): UpdateUserInfoRequest {
    return UpdateUserInfoRequestToJSONTyped(json, false);
}

export function UpdateUserInfoRequestToJSONTyped(value?: UpdateUserInfoRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'display_name': value['displayName'],
    };
}

