/* tslint:disable */
/* eslint-disable */
/**
 * TeamUp API
 * Sports venue booking and team formation API  Features: - Venue search with geolocation - Timeslot booking - TeamUp creation and management - Join request workflow 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VenueCreateIn
 */
export interface VenueCreateIn {
    /**
     * 
     * @type {string}
     * @memberof VenueCreateIn
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof VenueCreateIn
     */
    address: string;
    /**
     * 
     * @type {string}
     * @memberof VenueCreateIn
     */
    city?: string | null;
    /**
     * 
     * @type {number}
     * @memberof VenueCreateIn
     */
    latitude?: number | null;
    /**
     * 
     * @type {number}
     * @memberof VenueCreateIn
     */
    longitude?: number | null;
    /**
     * 
     * @type {string}
     * @memberof VenueCreateIn
     */
    contactPhone?: string | null;
    /**
     * 
     * @type {string}
     * @memberof VenueCreateIn
     */
    partnerCode?: string | null;
}

/**
 * Check if a given object implements the VenueCreateIn interface.
 */
export function instanceOfVenueCreateIn(value: object): value is VenueCreateIn {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('address' in value) || value['address'] === undefined) return false;
    return true;
}

export function VenueCreateInFromJSON(json: any): VenueCreateIn {
    return VenueCreateInFromJSONTyped(json, false);
}

export function VenueCreateInFromJSONTyped(json: any, ignoreDiscriminator: boolean): VenueCreateIn {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'address': json['address'],
        'city': json['city'] == null ? undefined : json['city'],
        'latitude': json['latitude'] == null ? undefined : json['latitude'],
        'longitude': json['longitude'] == null ? undefined : json['longitude'],
        'contactPhone': json['contact_phone'] == null ? undefined : json['contact_phone'],
        'partnerCode': json['partner_code'] == null ? undefined : json['partner_code'],
    };
}

export function VenueCreateInToJSON(json: any): VenueCreateIn {
    return VenueCreateInToJSONTyped(json, false);
}

export function VenueCreateInToJSONTyped(value?: VenueCreateIn | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'address': value['address'],
        'city': value['city'],
        'latitude': value['latitude'],
        'longitude': value['longitude'],
        'contact_phone': value['contactPhone'],
        'partner_code': value['partnerCode'],
    };
}

