/* tslint:disable */
/* eslint-disable */
/**
 * TeamUp API
 * Sports venue booking and team formation API  Features: - Venue search with geolocation - Timeslot booking - TeamUp creation and management - Join request workflow 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { VenueOut } from './VenueOut';
import {
    VenueOutFromJSON,
    VenueOutFromJSONTyped,
    VenueOutToJSON,
    VenueOutToJSONTyped,
} from './VenueOut';
import type { TimeSlotOut } from './TimeSlotOut';
import {
    TimeSlotOutFromJSON,
    TimeSlotOutFromJSONTyped,
    TimeSlotOutToJSON,
    TimeSlotOutToJSONTyped,
} from './TimeSlotOut';

/**
 * 
 * @export
 * @interface VenueSearchResult
 */
export interface VenueSearchResult {
    /**
     * 
     * @type {VenueOut}
     * @memberof VenueSearchResult
     */
    venue: VenueOut;
    /**
     * 
     * @type {Array<TimeSlotOut>}
     * @memberof VenueSearchResult
     */
    timeSlots: Array<TimeSlotOut>;
}

/**
 * Check if a given object implements the VenueSearchResult interface.
 */
export function instanceOfVenueSearchResult(value: object): value is VenueSearchResult {
    if (!('venue' in value) || value['venue'] === undefined) return false;
    if (!('timeSlots' in value) || value['timeSlots'] === undefined) return false;
    return true;
}

export function VenueSearchResultFromJSON(json: any): VenueSearchResult {
    return VenueSearchResultFromJSONTyped(json, false);
}

export function VenueSearchResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): VenueSearchResult {
    if (json == null) {
        return json;
    }
    return {
        
        'venue': VenueOutFromJSON(json['venue']),
        'timeSlots': ((json['time_slots'] as Array<any>).map(TimeSlotOutFromJSON)),
    };
}

export function VenueSearchResultToJSON(json: any): VenueSearchResult {
    return VenueSearchResultToJSONTyped(json, false);
}

export function VenueSearchResultToJSONTyped(value?: VenueSearchResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'venue': VenueOutToJSON(value['venue']),
        'time_slots': ((value['timeSlots'] as Array<any>).map(TimeSlotOutToJSON)),
    };
}

