/* tslint:disable */
/* eslint-disable */
/**
 * TeamUp API
 * Sports venue booking and team formation API  Features: - Venue search with geolocation - Timeslot booking - TeamUp creation and management - Join request workflow 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BookingOut
 */
export interface BookingOut {
    /**
     * 
     * @type {string}
     * @memberof BookingOut
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof BookingOut
     */
    ownerUserId: string;
    /**
     * 
     * @type {string}
     * @memberof BookingOut
     */
    timeSlotId: string;
    /**
     * 
     * @type {string}
     * @memberof BookingOut
     */
    teamupId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BookingOut
     */
    status: BookingOutStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof BookingOut
     */
    paymentStatus: BookingOutPaymentStatusEnum;
    /**
     * 
     * @type {Date}
     * @memberof BookingOut
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof BookingOut
     */
    updatedAt: Date;
}


/**
 * @export
 */
export const BookingOutStatusEnum = {
    pending: 'pending',
    confirmed: 'confirmed',
    cancelled: 'cancelled'
} as const;
export type BookingOutStatusEnum = typeof BookingOutStatusEnum[keyof typeof BookingOutStatusEnum];

/**
 * @export
 */
export const BookingOutPaymentStatusEnum = {
    none: 'none',
    pending: 'pending',
    succeeded: 'succeeded',
    failed: 'failed'
} as const;
export type BookingOutPaymentStatusEnum = typeof BookingOutPaymentStatusEnum[keyof typeof BookingOutPaymentStatusEnum];


/**
 * Check if a given object implements the BookingOut interface.
 */
export function instanceOfBookingOut(value: object): value is BookingOut {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('ownerUserId' in value) || value['ownerUserId'] === undefined) return false;
    if (!('timeSlotId' in value) || value['timeSlotId'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('paymentStatus' in value) || value['paymentStatus'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function BookingOutFromJSON(json: any): BookingOut {
    return BookingOutFromJSONTyped(json, false);
}

export function BookingOutFromJSONTyped(json: any, ignoreDiscriminator: boolean): BookingOut {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'ownerUserId': json['owner_user_id'],
        'timeSlotId': json['time_slot_id'],
        'teamupId': json['teamup_id'] == null ? undefined : json['teamup_id'],
        'status': json['status'],
        'paymentStatus': json['payment_status'],
        'createdAt': (new Date(json['created_at'])),
        'updatedAt': (new Date(json['updated_at'])),
    };
}

export function BookingOutToJSON(json: any): BookingOut {
    return BookingOutToJSONTyped(json, false);
}

export function BookingOutToJSONTyped(value?: BookingOut | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'owner_user_id': value['ownerUserId'],
        'time_slot_id': value['timeSlotId'],
        'teamup_id': value['teamupId'],
        'status': value['status'],
        'payment_status': value['paymentStatus'],
        'created_at': value['createdAt'].toISOString(),
        'updated_at': value['updatedAt'].toISOString(),
    };
}

