/* tslint:disable */
/* eslint-disable */
/**
 * TeamUp API
 * Sports venue booking and team formation API  Features: - Venue search with geolocation - Timeslot booking - TeamUp creation and management - Join request workflow 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BookingCreateIn
 */
export interface BookingCreateIn {
    /**
     * 
     * @type {string}
     * @memberof BookingCreateIn
     */
    timeSlotId: string;
    /**
     * Optional TeamUp association
     * @type {string}
     * @memberof BookingCreateIn
     */
    eventId?: string | null;
}

/**
 * Check if a given object implements the BookingCreateIn interface.
 */
export function instanceOfBookingCreateIn(value: object): value is BookingCreateIn {
    if (!('timeSlotId' in value) || value['timeSlotId'] === undefined) return false;
    return true;
}

export function BookingCreateInFromJSON(json: any): BookingCreateIn {
    return BookingCreateInFromJSONTyped(json, false);
}

export function BookingCreateInFromJSONTyped(json: any, ignoreDiscriminator: boolean): BookingCreateIn {
    if (json == null) {
        return json;
    }
    return {
        
        'timeSlotId': json['time_slot_id'],
        'eventId': json['event_id'] == null ? undefined : json['event_id'],
    };
}

export function BookingCreateInToJSON(json: any): BookingCreateIn {
    return BookingCreateInToJSONTyped(json, false);
}

export function BookingCreateInToJSONTyped(value?: BookingCreateIn | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'time_slot_id': value['timeSlotId'],
        'event_id': value['eventId'],
    };
}

