/* tslint:disable */
/* eslint-disable */
/**
 * TeamUp API
 * Sports venue booking and team formation API  Features: - Venue search with geolocation - Timeslot booking - TeamUp creation and management - Join request workflow 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BookingUpdateIn
 */
export interface BookingUpdateIn {
    /**
     * 
     * @type {string}
     * @memberof BookingUpdateIn
     */
    status?: BookingUpdateInStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof BookingUpdateIn
     */
    paymentStatus?: BookingUpdateInPaymentStatusEnum;
}


/**
 * @export
 */
export const BookingUpdateInStatusEnum = {
    pending: 'pending',
    confirmed: 'confirmed',
    cancelled: 'cancelled'
} as const;
export type BookingUpdateInStatusEnum = typeof BookingUpdateInStatusEnum[keyof typeof BookingUpdateInStatusEnum];

/**
 * @export
 */
export const BookingUpdateInPaymentStatusEnum = {
    none: 'none',
    pending: 'pending',
    succeeded: 'succeeded',
    failed: 'failed'
} as const;
export type BookingUpdateInPaymentStatusEnum = typeof BookingUpdateInPaymentStatusEnum[keyof typeof BookingUpdateInPaymentStatusEnum];


/**
 * Check if a given object implements the BookingUpdateIn interface.
 */
export function instanceOfBookingUpdateIn(value: object): value is BookingUpdateIn {
    return true;
}

export function BookingUpdateInFromJSON(json: any): BookingUpdateIn {
    return BookingUpdateInFromJSONTyped(json, false);
}

export function BookingUpdateInFromJSONTyped(json: any, ignoreDiscriminator: boolean): BookingUpdateIn {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'] == null ? undefined : json['status'],
        'paymentStatus': json['payment_status'] == null ? undefined : json['payment_status'],
    };
}

export function BookingUpdateInToJSON(json: any): BookingUpdateIn {
    return BookingUpdateInToJSONTyped(json, false);
}

export function BookingUpdateInToJSONTyped(value?: BookingUpdateIn | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'payment_status': value['paymentStatus'],
    };
}

