/* tslint:disable */
/* eslint-disable */
/**
 * TeamUp API
 * Sports venue booking and team formation API  Features: - Venue search with geolocation - Timeslot booking - TeamUp creation and management - Join request workflow 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { VenueOut } from './VenueOut';
import {
    VenueOutFromJSON,
    VenueOutFromJSONTyped,
    VenueOutToJSON,
    VenueOutToJSONTyped,
} from './VenueOut';
import type { TimeSlotOut } from './TimeSlotOut';
import {
    TimeSlotOutFromJSON,
    TimeSlotOutFromJSONTyped,
    TimeSlotOutToJSON,
    TimeSlotOutToJSONTyped,
} from './TimeSlotOut';
import type { CourtOut } from './CourtOut';
import {
    CourtOutFromJSON,
    CourtOutFromJSONTyped,
    CourtOutToJSON,
    CourtOutToJSONTyped,
} from './CourtOut';
import type { EventOut } from './EventOut';
import {
    EventOutFromJSON,
    EventOutFromJSONTyped,
    EventOutToJSON,
    EventOutToJSONTyped,
} from './EventOut';

/**
 * 
 * @export
 * @interface BookingDetailOut
 */
export interface BookingDetailOut {
    /**
     * 
     * @type {string}
     * @memberof BookingDetailOut
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof BookingDetailOut
     */
    ownerUserId: string;
    /**
     * 
     * @type {string}
     * @memberof BookingDetailOut
     */
    timeSlotId: string;
    /**
     * 
     * @type {string}
     * @memberof BookingDetailOut
     */
    eventId?: string | null;
    /**
     * 
     * @type {BookingDetailOutStatusEnum}
     * @memberof BookingDetailOut
     */
    status: BookingDetailOutStatusEnum;
    /**
     * 
     * @type {BookingDetailOutPaymentStatusEnum}
     * @memberof BookingDetailOut
     */
    paymentStatus: BookingDetailOutPaymentStatusEnum;
    /**
     * 
     * @type {TimeSlotOut}
     * @memberof BookingDetailOut
     */
    timeSlot: TimeSlotOut;
    /**
     * 
     * @type {CourtOut}
     * @memberof BookingDetailOut
     */
    court: CourtOut;
    /**
     * 
     * @type {VenueOut}
     * @memberof BookingDetailOut
     */
    venue: VenueOut;
    /**
     * 
     * @type {EventOut}
     * @memberof BookingDetailOut
     */
    event?: EventOut;
    /**
     * 
     * @type {Date}
     * @memberof BookingDetailOut
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof BookingDetailOut
     */
    updatedAt: Date;
}


/**
 * @export
 */
export const BookingDetailOutStatusEnum = {
    Pending: 'pending',
    Confirmed: 'confirmed',
    Cancelled: 'cancelled'
} as const;
export type BookingDetailOutStatusEnum = typeof BookingDetailOutStatusEnum[keyof typeof BookingDetailOutStatusEnum];

/**
 * @export
 */
export const BookingDetailOutPaymentStatusEnum = {
    None: 'none',
    Pending: 'pending',
    Succeeded: 'succeeded',
    Failed: 'failed'
} as const;
export type BookingDetailOutPaymentStatusEnum = typeof BookingDetailOutPaymentStatusEnum[keyof typeof BookingDetailOutPaymentStatusEnum];


/**
 * Check if a given object implements the BookingDetailOut interface.
 */
export function instanceOfBookingDetailOut(value: object): value is BookingDetailOut {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('ownerUserId' in value) || value['ownerUserId'] === undefined) return false;
    if (!('timeSlotId' in value) || value['timeSlotId'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('paymentStatus' in value) || value['paymentStatus'] === undefined) return false;
    if (!('timeSlot' in value) || value['timeSlot'] === undefined) return false;
    if (!('court' in value) || value['court'] === undefined) return false;
    if (!('venue' in value) || value['venue'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function BookingDetailOutFromJSON(json: any): BookingDetailOut {
    return BookingDetailOutFromJSONTyped(json, false);
}

export function BookingDetailOutFromJSONTyped(json: any, ignoreDiscriminator: boolean): BookingDetailOut {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'ownerUserId': json['owner_user_id'],
        'timeSlotId': json['time_slot_id'],
        'eventId': json['event_id'] == null ? undefined : json['event_id'],
        'status': json['status'],
        'paymentStatus': json['payment_status'],
        'timeSlot': TimeSlotOutFromJSON(json['time_slot']),
        'court': CourtOutFromJSON(json['court']),
        'venue': VenueOutFromJSON(json['venue']),
        'event': json['event'] == null ? undefined : EventOutFromJSON(json['event']),
        'createdAt': (new Date(json['created_at'])),
        'updatedAt': (new Date(json['updated_at'])),
    };
}

export function BookingDetailOutToJSON(json: any): BookingDetailOut {
    return BookingDetailOutToJSONTyped(json, false);
}

export function BookingDetailOutToJSONTyped(value?: BookingDetailOut | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'owner_user_id': value['ownerUserId'],
        'time_slot_id': value['timeSlotId'],
        'event_id': value['eventId'],
        'status': value['status'],
        'payment_status': value['paymentStatus'],
        'time_slot': TimeSlotOutToJSON(value['timeSlot']),
        'court': CourtOutToJSON(value['court']),
        'venue': VenueOutToJSON(value['venue']),
        'event': EventOutToJSON(value['event']),
        'created_at': value['createdAt'].toISOString(),
        'updated_at': value['updatedAt'].toISOString(),
    };
}

