/* tslint:disable */
/* eslint-disable */
/**
 * TeamUp API
 * Sports venue booking and team formation API  Features: - Venue search with geolocation - Timeslot booking - TeamUp creation and management - Join request workflow 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ChatMessageOut
 */
export interface ChatMessageOut {
    /**
     * 
     * @type {string}
     * @memberof ChatMessageOut
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ChatMessageOut
     */
    userId: string;
    /**
     * 
     * @type {string}
     * @memberof ChatMessageOut
     */
    role: ChatMessageOutRoleEnum;
    /**
     * 
     * @type {string}
     * @memberof ChatMessageOut
     */
    content: string;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof ChatMessageOut
     */
    widget?: { [key: string]: any; } | null;
    /**
     * 
     * @type {Date}
     * @memberof ChatMessageOut
     */
    createdAt: Date;
}


/**
 * @export
 */
export const ChatMessageOutRoleEnum = {
    user: 'user',
    assistant: 'assistant'
} as const;
export type ChatMessageOutRoleEnum = typeof ChatMessageOutRoleEnum[keyof typeof ChatMessageOutRoleEnum];


/**
 * Check if a given object implements the ChatMessageOut interface.
 */
export function instanceOfChatMessageOut(value: object): value is ChatMessageOut {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('userId' in value) || value['userId'] === undefined) return false;
    if (!('role' in value) || value['role'] === undefined) return false;
    if (!('content' in value) || value['content'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function ChatMessageOutFromJSON(json: any): ChatMessageOut {
    return ChatMessageOutFromJSONTyped(json, false);
}

export function ChatMessageOutFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChatMessageOut {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'userId': json['user_id'],
        'role': json['role'],
        'content': json['content'],
        'widget': json['widget'] == null ? undefined : json['widget'],
        'createdAt': (new Date(json['created_at'])),
    };
}

export function ChatMessageOutToJSON(json: any): ChatMessageOut {
    return ChatMessageOutToJSONTyped(json, false);
}

export function ChatMessageOutToJSONTyped(value?: ChatMessageOut | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'user_id': value['userId'],
        'role': value['role'],
        'content': value['content'],
        'widget': value['widget'],
        'created_at': value['createdAt'].toISOString(),
    };
}

