/* tslint:disable */
/* eslint-disable */
/**
 * TeamUp API
 * Sports venue booking and team formation API  Features: - Venue search with geolocation - Timeslot booking - TeamUp creation and management - Join request workflow 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CourtOut
 */
export interface CourtOut {
    /**
     * 
     * @type {string}
     * @memberof CourtOut
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof CourtOut
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof CourtOut
     */
    sportType?: string | null;
}

/**
 * Check if a given object implements the CourtOut interface.
 */
export function instanceOfCourtOut(value: object): value is CourtOut {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function CourtOutFromJSON(json: any): CourtOut {
    return CourtOutFromJSONTyped(json, false);
}

export function CourtOutFromJSONTyped(json: any, ignoreDiscriminator: boolean): CourtOut {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'sportType': json['sport_type'] == null ? undefined : json['sport_type'],
    };
}

export function CourtOutToJSON(json: any): CourtOut {
    return CourtOutToJSONTyped(json, false);
}

export function CourtOutToJSONTyped(value?: CourtOut | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'sport_type': value['sportType'],
    };
}

