/* tslint:disable */
/* eslint-disable */
/**
 * TeamUp API
 * Sports venue booking and team formation API  Features: - Venue search with geolocation - Timeslot booking - TeamUp creation and management - Join request workflow 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EventParticipantOut
 */
export interface EventParticipantOut {
    /**
     * 
     * @type {string}
     * @memberof EventParticipantOut
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof EventParticipantOut
     */
    userId: string;
    /**
     * 
     * @type {string}
     * @memberof EventParticipantOut
     */
    displayName: string;
    /**
     * 
     * @type {string}
     * @memberof EventParticipantOut
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof EventParticipantOut
     */
    phone: string;
    /**
     * 
     * @type {string}
     * @memberof EventParticipantOut
     */
    role: EventParticipantOutRoleEnum;
    /**
     * 
     * @type {string}
     * @memberof EventParticipantOut
     */
    avatarUrl?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof EventParticipantOut
     */
    joinedAt: Date;
}


/**
 * @export
 */
export const EventParticipantOutRoleEnum = {
    owner: 'owner',
    member: 'member'
} as const;
export type EventParticipantOutRoleEnum = typeof EventParticipantOutRoleEnum[keyof typeof EventParticipantOutRoleEnum];


/**
 * Check if a given object implements the EventParticipantOut interface.
 */
export function instanceOfEventParticipantOut(value: object): value is EventParticipantOut {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('userId' in value) || value['userId'] === undefined) return false;
    if (!('displayName' in value) || value['displayName'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('phone' in value) || value['phone'] === undefined) return false;
    if (!('role' in value) || value['role'] === undefined) return false;
    if (!('joinedAt' in value) || value['joinedAt'] === undefined) return false;
    return true;
}

export function EventParticipantOutFromJSON(json: any): EventParticipantOut {
    return EventParticipantOutFromJSONTyped(json, false);
}

export function EventParticipantOutFromJSONTyped(json: any, ignoreDiscriminator: boolean): EventParticipantOut {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'userId': json['user_id'],
        'displayName': json['display_name'],
        'email': json['email'],
        'phone': json['phone'],
        'role': json['role'],
        'avatarUrl': json['avatar_url'] == null ? undefined : json['avatar_url'],
        'joinedAt': (new Date(json['joined_at'])),
    };
}

export function EventParticipantOutToJSON(json: any): EventParticipantOut {
    return EventParticipantOutToJSONTyped(json, false);
}

export function EventParticipantOutToJSONTyped(value?: EventParticipantOut | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'user_id': value['userId'],
        'display_name': value['displayName'],
        'email': value['email'],
        'phone': value['phone'],
        'role': value['role'],
        'avatar_url': value['avatarUrl'],
        'joined_at': value['joinedAt'].toISOString(),
    };
}

