/* tslint:disable */
/* eslint-disable */
/**
 * TeamUp API
 * Sports venue booking and team formation API  Features: - Venue search with geolocation - Timeslot booking - TeamUp creation and management - Join request workflow 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EventCreateIn
 */
export interface EventCreateIn {
    /**
     * 
     * @type {string}
     * @memberof EventCreateIn
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof EventCreateIn
     */
    description?: string | null;
    /**
     * 
     * @type {number}
     * @memberof EventCreateIn
     */
    maxParticipants: number;
    /**
     * Optional Venue association
     * @type {string}
     * @memberof EventCreateIn
     */
    venueId?: string | null;
    /**
     * Optional Court association
     * @type {string}
     * @memberof EventCreateIn
     */
    courtId?: string | null;
    /**
     * 
     * @type {EventCreateInVisibilityEnum}
     * @memberof EventCreateIn
     */
    visibility?: EventCreateInVisibilityEnum;
    /**
     * 
     * @type {EventCreateInDurationTypeEnum}
     * @memberof EventCreateIn
     */
    durationType?: EventCreateInDurationTypeEnum;
    /**
     * 
     * @type {EventCreateInStatusEnum}
     * @memberof EventCreateIn
     */
    status?: EventCreateInStatusEnum;
}


/**
 * @export
 */
export const EventCreateInVisibilityEnum = {
    Public: 'public',
    Private: 'private'
} as const;
export type EventCreateInVisibilityEnum = typeof EventCreateInVisibilityEnum[keyof typeof EventCreateInVisibilityEnum];

/**
 * @export
 */
export const EventCreateInDurationTypeEnum = {
    Temporary: 'temporary',
    Permanent: 'permanent'
} as const;
export type EventCreateInDurationTypeEnum = typeof EventCreateInDurationTypeEnum[keyof typeof EventCreateInDurationTypeEnum];

/**
 * @export
 */
export const EventCreateInStatusEnum = {
    Open: 'open',
    Closed: 'closed'
} as const;
export type EventCreateInStatusEnum = typeof EventCreateInStatusEnum[keyof typeof EventCreateInStatusEnum];


/**
 * Check if a given object implements the EventCreateIn interface.
 */
export function instanceOfEventCreateIn(value: object): value is EventCreateIn {
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('maxParticipants' in value) || value['maxParticipants'] === undefined) return false;
    return true;
}

export function EventCreateInFromJSON(json: any): EventCreateIn {
    return EventCreateInFromJSONTyped(json, false);
}

export function EventCreateInFromJSONTyped(json: any, ignoreDiscriminator: boolean): EventCreateIn {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'maxParticipants': json['max_participants'],
        'venueId': json['venue_id'] == null ? undefined : json['venue_id'],
        'courtId': json['court_id'] == null ? undefined : json['court_id'],
        'visibility': json['visibility'] == null ? undefined : json['visibility'],
        'durationType': json['duration_type'] == null ? undefined : json['duration_type'],
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function EventCreateInToJSON(json: any): EventCreateIn {
    return EventCreateInToJSONTyped(json, false);
}

export function EventCreateInToJSONTyped(value?: EventCreateIn | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'description': value['description'],
        'max_participants': value['maxParticipants'],
        'venue_id': value['venueId'],
        'court_id': value['courtId'],
        'visibility': value['visibility'],
        'duration_type': value['durationType'],
        'status': value['status'],
    };
}

