/* tslint:disable */
/* eslint-disable */
/**
 * TeamUp API
 * Sports venue booking and team formation API  Features: - Venue search with geolocation - Timeslot booking - TeamUp creation and management - Join request workflow 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EventBookingResponse
 */
export interface EventBookingResponse {
    /**
     * 
     * @type {string}
     * @memberof EventBookingResponse
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof EventBookingResponse
     */
    eventId: string;
    /**
     * 
     * @type {string}
     * @memberof EventBookingResponse
     */
    timeSlotId: string;
    /**
     * 
     * @type {string}
     * @memberof EventBookingResponse
     */
    status: EventBookingResponseStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof EventBookingResponse
     */
    paymentStatus: EventBookingResponsePaymentStatusEnum;
    /**
     * 
     * @type {Date}
     * @memberof EventBookingResponse
     */
    createdAt: Date;
}


/**
 * @export
 */
export const EventBookingResponseStatusEnum = {
    pending: 'pending',
    confirmed: 'confirmed',
    cancelled: 'cancelled'
} as const;
export type EventBookingResponseStatusEnum = typeof EventBookingResponseStatusEnum[keyof typeof EventBookingResponseStatusEnum];

/**
 * @export
 */
export const EventBookingResponsePaymentStatusEnum = {
    none: 'none',
    pending: 'pending',
    succeeded: 'succeeded',
    failed: 'failed'
} as const;
export type EventBookingResponsePaymentStatusEnum = typeof EventBookingResponsePaymentStatusEnum[keyof typeof EventBookingResponsePaymentStatusEnum];


/**
 * Check if a given object implements the EventBookingResponse interface.
 */
export function instanceOfEventBookingResponse(value: object): value is EventBookingResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('eventId' in value) || value['eventId'] === undefined) return false;
    if (!('timeSlotId' in value) || value['timeSlotId'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('paymentStatus' in value) || value['paymentStatus'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function EventBookingResponseFromJSON(json: any): EventBookingResponse {
    return EventBookingResponseFromJSONTyped(json, false);
}

export function EventBookingResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): EventBookingResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'eventId': json['event_id'],
        'timeSlotId': json['time_slot_id'],
        'status': json['status'],
        'paymentStatus': json['payment_status'],
        'createdAt': (new Date(json['created_at'])),
    };
}

export function EventBookingResponseToJSON(json: any): EventBookingResponse {
    return EventBookingResponseToJSONTyped(json, false);
}

export function EventBookingResponseToJSONTyped(value?: EventBookingResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'event_id': value['eventId'],
        'time_slot_id': value['timeSlotId'],
        'status': value['status'],
        'payment_status': value['paymentStatus'],
        'created_at': value['createdAt'].toISOString(),
    };
}

