/* tslint:disable */
/* eslint-disable */
/**
 * TeamUp API
 * Sports venue booking and team formation API  Features: - Venue search with geolocation - Timeslot booking - TeamUp creation and management - Join request workflow 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { VenueOut } from './VenueOut';
import {
    VenueOutFromJSON,
    VenueOutFromJSONTyped,
    VenueOutToJSON,
    VenueOutToJSONTyped,
} from './VenueOut';
import type { TimeSlotOut } from './TimeSlotOut';
import {
    TimeSlotOutFromJSON,
    TimeSlotOutFromJSONTyped,
    TimeSlotOutToJSON,
    TimeSlotOutToJSONTyped,
} from './TimeSlotOut';
import type { CourtOut } from './CourtOut';
import {
    CourtOutFromJSON,
    CourtOutFromJSONTyped,
    CourtOutToJSON,
    CourtOutToJSONTyped,
} from './CourtOut';

/**
 * 
 * @export
 * @interface EventBookingDetail
 */
export interface EventBookingDetail {
    /**
     * 
     * @type {string}
     * @memberof EventBookingDetail
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof EventBookingDetail
     */
    status: EventBookingDetailStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof EventBookingDetail
     */
    paymentStatus: EventBookingDetailPaymentStatusEnum;
    /**
     * 
     * @type {TimeSlotOut}
     * @memberof EventBookingDetail
     */
    timeSlot: TimeSlotOut;
    /**
     * 
     * @type {CourtOut}
     * @memberof EventBookingDetail
     */
    court: CourtOut;
    /**
     * 
     * @type {VenueOut}
     * @memberof EventBookingDetail
     */
    venue: VenueOut;
    /**
     * 
     * @type {Date}
     * @memberof EventBookingDetail
     */
    createdAt?: Date;
}


/**
 * @export
 */
export const EventBookingDetailStatusEnum = {
    pending: 'pending',
    confirmed: 'confirmed',
    cancelled: 'cancelled'
} as const;
export type EventBookingDetailStatusEnum = typeof EventBookingDetailStatusEnum[keyof typeof EventBookingDetailStatusEnum];

/**
 * @export
 */
export const EventBookingDetailPaymentStatusEnum = {
    none: 'none',
    pending: 'pending',
    succeeded: 'succeeded',
    failed: 'failed'
} as const;
export type EventBookingDetailPaymentStatusEnum = typeof EventBookingDetailPaymentStatusEnum[keyof typeof EventBookingDetailPaymentStatusEnum];


/**
 * Check if a given object implements the EventBookingDetail interface.
 */
export function instanceOfEventBookingDetail(value: object): value is EventBookingDetail {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('paymentStatus' in value) || value['paymentStatus'] === undefined) return false;
    if (!('timeSlot' in value) || value['timeSlot'] === undefined) return false;
    if (!('court' in value) || value['court'] === undefined) return false;
    if (!('venue' in value) || value['venue'] === undefined) return false;
    return true;
}

export function EventBookingDetailFromJSON(json: any): EventBookingDetail {
    return EventBookingDetailFromJSONTyped(json, false);
}

export function EventBookingDetailFromJSONTyped(json: any, ignoreDiscriminator: boolean): EventBookingDetail {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'status': json['status'],
        'paymentStatus': json['payment_status'],
        'timeSlot': TimeSlotOutFromJSON(json['time_slot']),
        'court': CourtOutFromJSON(json['court']),
        'venue': VenueOutFromJSON(json['venue']),
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
    };
}

export function EventBookingDetailToJSON(json: any): EventBookingDetail {
    return EventBookingDetailToJSONTyped(json, false);
}

export function EventBookingDetailToJSONTyped(value?: EventBookingDetail | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'status': value['status'],
        'payment_status': value['paymentStatus'],
        'time_slot': TimeSlotOutToJSON(value['timeSlot']),
        'court': CourtOutToJSON(value['court']),
        'venue': VenueOutToJSON(value['venue']),
        'created_at': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
    };
}

