/* tslint:disable */
/* eslint-disable */
/**
 * TeamUp API
 * Sports venue booking and team formation API  Features: - Venue search with geolocation - Timeslot booking - TeamUp creation and management - Join request workflow 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface JoinRequestSubmitResponse
 */
export interface JoinRequestSubmitResponse {
    /**
     * 
     * @type {string}
     * @memberof JoinRequestSubmitResponse
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof JoinRequestSubmitResponse
     */
    status: JoinRequestSubmitResponseStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof JoinRequestSubmitResponse
     */
    message: string;
}


/**
 * @export
 */
export const JoinRequestSubmitResponseStatusEnum = {
    submitted: 'submitted',
    approved: 'approved',
    rejected: 'rejected'
} as const;
export type JoinRequestSubmitResponseStatusEnum = typeof JoinRequestSubmitResponseStatusEnum[keyof typeof JoinRequestSubmitResponseStatusEnum];


/**
 * Check if a given object implements the JoinRequestSubmitResponse interface.
 */
export function instanceOfJoinRequestSubmitResponse(value: object): value is JoinRequestSubmitResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function JoinRequestSubmitResponseFromJSON(json: any): JoinRequestSubmitResponse {
    return JoinRequestSubmitResponseFromJSONTyped(json, false);
}

export function JoinRequestSubmitResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): JoinRequestSubmitResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'status': json['status'],
        'message': json['message'],
    };
}

export function JoinRequestSubmitResponseToJSON(json: any): JoinRequestSubmitResponse {
    return JoinRequestSubmitResponseToJSONTyped(json, false);
}

export function JoinRequestSubmitResponseToJSONTyped(value?: JoinRequestSubmitResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'status': value['status'],
        'message': value['message'],
    };
}

