/* tslint:disable */
/* eslint-disable */
/**
 * TeamUp API
 * Sports venue booking and team formation API  Features: - Venue search with geolocation - Timeslot booking - TeamUp creation and management - Join request workflow 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MarkNotificationAsRead200Response
 */
export interface MarkNotificationAsRead200Response {
    /**
     * 
     * @type {string}
     * @memberof MarkNotificationAsRead200Response
     */
    message?: string;
}

/**
 * Check if a given object implements the MarkNotificationAsRead200Response interface.
 */
export function instanceOfMarkNotificationAsRead200Response(value: object): value is MarkNotificationAsRead200Response {
    return true;
}

export function MarkNotificationAsRead200ResponseFromJSON(json: any): MarkNotificationAsRead200Response {
    return MarkNotificationAsRead200ResponseFromJSONTyped(json, false);
}

export function MarkNotificationAsRead200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MarkNotificationAsRead200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function MarkNotificationAsRead200ResponseToJSON(json: any): MarkNotificationAsRead200Response {
    return MarkNotificationAsRead200ResponseToJSONTyped(json, false);
}

export function MarkNotificationAsRead200ResponseToJSONTyped(value?: MarkNotificationAsRead200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
    };
}

