/* tslint:disable */
/* eslint-disable */
/**
 * TeamUp API
 * Sports venue booking and team formation API  Features: - Venue search with geolocation - Timeslot booking - TeamUp creation and management - Join request workflow 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MatchedEventSummary
 */
export interface MatchedEventSummary {
    /**
     * 
     * @type {string}
     * @memberof MatchedEventSummary
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof MatchedEventSummary
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof MatchedEventSummary
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof MatchedEventSummary
     */
    sportType?: string;
    /**
     * 
     * @type {string}
     * @memberof MatchedEventSummary
     */
    status: MatchedEventSummaryStatusEnum;
    /**
     * 
     * @type {Date}
     * @memberof MatchedEventSummary
     */
    startTime?: Date | null;
}


/**
 * @export
 */
export const MatchedEventSummaryStatusEnum = {
    open: 'open',
    closed: 'closed'
} as const;
export type MatchedEventSummaryStatusEnum = typeof MatchedEventSummaryStatusEnum[keyof typeof MatchedEventSummaryStatusEnum];


/**
 * Check if a given object implements the MatchedEventSummary interface.
 */
export function instanceOfMatchedEventSummary(value: object): value is MatchedEventSummary {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function MatchedEventSummaryFromJSON(json: any): MatchedEventSummary {
    return MatchedEventSummaryFromJSONTyped(json, false);
}

export function MatchedEventSummaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): MatchedEventSummary {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'title': json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'sportType': json['sport_type'] == null ? undefined : json['sport_type'],
        'status': json['status'],
        'startTime': json['start_time'] == null ? undefined : (new Date(json['start_time'])),
    };
}

export function MatchedEventSummaryToJSON(json: any): MatchedEventSummary {
    return MatchedEventSummaryToJSONTyped(json, false);
}

export function MatchedEventSummaryToJSONTyped(value?: MatchedEventSummary | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'title': value['title'],
        'description': value['description'],
        'sport_type': value['sportType'],
        'status': value['status'],
        'start_time': value['startTime'] == null ? value['startTime'] : value['startTime'].toISOString(),
    };
}

