/* tslint:disable */
/* eslint-disable */
/**
 * TeamUp API
 * Sports venue booking and team formation API  Features: - Venue search with geolocation - Timeslot booking - TeamUp creation and management - Join request workflow 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TicketOut
 */
export interface TicketOut {
    /**
     * 
     * @type {string}
     * @memberof TicketOut
     */
    id: string;
    /**
     * 
     * @type {Date}
     * @memberof TicketOut
     */
    date: Date;
    /**
     * 
     * @type {string}
     * @memberof TicketOut
     */
    startTime: string;
    /**
     * 
     * @type {string}
     * @memberof TicketOut
     */
    sportType: string;
    /**
     * 
     * @type {string}
     * @memberof TicketOut
     */
    intensity?: string;
    /**
     * 
     * @type {string}
     * @memberof TicketOut
     */
    status: TicketOutStatusEnum;
    /**
     * 
     * @type {Date}
     * @memberof TicketOut
     */
    createdAt: Date;
    /**
     * 
     * @type {string}
     * @memberof TicketOut
     */
    message?: string | null;
}


/**
 * @export
 */
export const TicketOutStatusEnum = {
    open: 'open',
    matched: 'matched',
    expired: 'expired'
} as const;
export type TicketOutStatusEnum = typeof TicketOutStatusEnum[keyof typeof TicketOutStatusEnum];


/**
 * Check if a given object implements the TicketOut interface.
 */
export function instanceOfTicketOut(value: object): value is TicketOut {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('date' in value) || value['date'] === undefined) return false;
    if (!('startTime' in value) || value['startTime'] === undefined) return false;
    if (!('sportType' in value) || value['sportType'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function TicketOutFromJSON(json: any): TicketOut {
    return TicketOutFromJSONTyped(json, false);
}

export function TicketOutFromJSONTyped(json: any, ignoreDiscriminator: boolean): TicketOut {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'date': (new Date(json['date'])),
        'startTime': json['start_time'],
        'sportType': json['sport_type'],
        'intensity': json['intensity'] == null ? undefined : json['intensity'],
        'status': json['status'],
        'createdAt': (new Date(json['created_at'])),
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function TicketOutToJSON(json: any): TicketOut {
    return TicketOutToJSONTyped(json, false);
}

export function TicketOutToJSONTyped(value?: TicketOut | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'date': value['date'].toISOString().substring(0,10),
        'start_time': value['startTime'],
        'sport_type': value['sportType'],
        'intensity': value['intensity'],
        'status': value['status'],
        'created_at': value['createdAt'].toISOString(),
        'message': value['message'],
    };
}

