/* tslint:disable */
/* eslint-disable */
/**
 * TeamUp API
 * Sports venue booking and team formation API  Features: - Venue search with geolocation - Timeslot booking - TeamUp creation and management - Join request workflow 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TicketUpdateIn
 */
export interface TicketUpdateIn {
    /**
     * 
     * @type {Date}
     * @memberof TicketUpdateIn
     */
    date?: Date;
    /**
     * 
     * @type {string}
     * @memberof TicketUpdateIn
     */
    startTime?: string;
    /**
     * 
     * @type {number}
     * @memberof TicketUpdateIn
     */
    durationMinutes?: number;
    /**
     * 
     * @type {string}
     * @memberof TicketUpdateIn
     */
    sportType?: string;
    /**
     * 
     * @type {TicketUpdateInIntensityEnum}
     * @memberof TicketUpdateIn
     */
    intensity?: TicketUpdateInIntensityEnum;
    /**
     * 
     * @type {Array<string>}
     * @memberof TicketUpdateIn
     */
    venueIds?: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof TicketUpdateIn
     */
    priceMin?: number | null;
    /**
     * 
     * @type {number}
     * @memberof TicketUpdateIn
     */
    priceMax?: number | null;
    /**
     * 
     * @type {string}
     * @memberof TicketUpdateIn
     */
    currency?: string;
}


/**
 * @export
 */
export const TicketUpdateInIntensityEnum = {
    Low: 'Low',
    Medium: 'Medium',
    High: 'High'
} as const;
export type TicketUpdateInIntensityEnum = typeof TicketUpdateInIntensityEnum[keyof typeof TicketUpdateInIntensityEnum];


/**
 * Check if a given object implements the TicketUpdateIn interface.
 */
export function instanceOfTicketUpdateIn(value: object): value is TicketUpdateIn {
    return true;
}

export function TicketUpdateInFromJSON(json: any): TicketUpdateIn {
    return TicketUpdateInFromJSONTyped(json, false);
}

export function TicketUpdateInFromJSONTyped(json: any, ignoreDiscriminator: boolean): TicketUpdateIn {
    if (json == null) {
        return json;
    }
    return {
        
        'date': json['date'] == null ? undefined : (new Date(json['date'])),
        'startTime': json['start_time'] == null ? undefined : json['start_time'],
        'durationMinutes': json['duration_minutes'] == null ? undefined : json['duration_minutes'],
        'sportType': json['sport_type'] == null ? undefined : json['sport_type'],
        'intensity': json['intensity'] == null ? undefined : json['intensity'],
        'venueIds': json['venue_ids'] == null ? undefined : json['venue_ids'],
        'priceMin': json['price_min'] == null ? undefined : json['price_min'],
        'priceMax': json['price_max'] == null ? undefined : json['price_max'],
        'currency': json['currency'] == null ? undefined : json['currency'],
    };
}

export function TicketUpdateInToJSON(json: any): TicketUpdateIn {
    return TicketUpdateInToJSONTyped(json, false);
}

export function TicketUpdateInToJSONTyped(value?: TicketUpdateIn | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'date': value['date'] == null ? value['date'] : value['date'].toISOString().substring(0,10),
        'start_time': value['startTime'],
        'duration_minutes': value['durationMinutes'],
        'sport_type': value['sportType'],
        'intensity': value['intensity'],
        'venue_ids': value['venueIds'],
        'price_min': value['priceMin'],
        'price_max': value['priceMax'],
        'currency': value['currency'],
    };
}

