/* tslint:disable */
/* eslint-disable */
/**
 * TeamUp API
 * Sports venue booking and team formation API  Features: - Venue search with geolocation - Timeslot booking - TeamUp creation and management - Join request workflow 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MatchedEventSummary } from './MatchedEventSummary';
import {
    MatchedEventSummaryFromJSON,
    MatchedEventSummaryFromJSONTyped,
    MatchedEventSummaryToJSON,
    MatchedEventSummaryToJSONTyped,
} from './MatchedEventSummary';

/**
 * 
 * @export
 * @interface TicketDetailOut
 */
export interface TicketDetailOut {
    /**
     * 
     * @type {string}
     * @memberof TicketDetailOut
     */
    id: string;
    /**
     * 
     * @type {Date}
     * @memberof TicketDetailOut
     */
    date: Date;
    /**
     * 
     * @type {string}
     * @memberof TicketDetailOut
     */
    startTime: string;
    /**
     * 
     * @type {number}
     * @memberof TicketDetailOut
     */
    durationMinutes: number;
    /**
     * 
     * @type {string}
     * @memberof TicketDetailOut
     */
    sportType: string;
    /**
     * 
     * @type {string}
     * @memberof TicketDetailOut
     */
    intensity: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof TicketDetailOut
     */
    venueIds?: Array<string> | null;
    /**
     * 
     * @type {number}
     * @memberof TicketDetailOut
     */
    priceMin?: number | null;
    /**
     * 
     * @type {number}
     * @memberof TicketDetailOut
     */
    priceMax?: number | null;
    /**
     * 
     * @type {string}
     * @memberof TicketDetailOut
     */
    currency?: string;
    /**
     * 
     * @type {string}
     * @memberof TicketDetailOut
     */
    status: TicketDetailOutStatusEnum;
    /**
     * 
     * @type {Date}
     * @memberof TicketDetailOut
     */
    createdAt: Date;
    /**
     * 
     * @type {Array<MatchedEventSummary>}
     * @memberof TicketDetailOut
     */
    matchedEvents: Array<MatchedEventSummary>;
}


/**
 * @export
 */
export const TicketDetailOutStatusEnum = {
    open: 'open',
    matched: 'matched',
    expired: 'expired'
} as const;
export type TicketDetailOutStatusEnum = typeof TicketDetailOutStatusEnum[keyof typeof TicketDetailOutStatusEnum];


/**
 * Check if a given object implements the TicketDetailOut interface.
 */
export function instanceOfTicketDetailOut(value: object): value is TicketDetailOut {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('date' in value) || value['date'] === undefined) return false;
    if (!('startTime' in value) || value['startTime'] === undefined) return false;
    if (!('durationMinutes' in value) || value['durationMinutes'] === undefined) return false;
    if (!('sportType' in value) || value['sportType'] === undefined) return false;
    if (!('intensity' in value) || value['intensity'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('matchedEvents' in value) || value['matchedEvents'] === undefined) return false;
    return true;
}

export function TicketDetailOutFromJSON(json: any): TicketDetailOut {
    return TicketDetailOutFromJSONTyped(json, false);
}

export function TicketDetailOutFromJSONTyped(json: any, ignoreDiscriminator: boolean): TicketDetailOut {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'date': (new Date(json['date'])),
        'startTime': json['start_time'],
        'durationMinutes': json['duration_minutes'],
        'sportType': json['sport_type'],
        'intensity': json['intensity'],
        'venueIds': json['venue_ids'] == null ? undefined : json['venue_ids'],
        'priceMin': json['price_min'] == null ? undefined : json['price_min'],
        'priceMax': json['price_max'] == null ? undefined : json['price_max'],
        'currency': json['currency'] == null ? undefined : json['currency'],
        'status': json['status'],
        'createdAt': (new Date(json['created_at'])),
        'matchedEvents': ((json['matched_events'] as Array<any>).map(MatchedEventSummaryFromJSON)),
    };
}

export function TicketDetailOutToJSON(json: any): TicketDetailOut {
    return TicketDetailOutToJSONTyped(json, false);
}

export function TicketDetailOutToJSONTyped(value?: TicketDetailOut | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'date': value['date'].toISOString().substring(0,10),
        'start_time': value['startTime'],
        'duration_minutes': value['durationMinutes'],
        'sport_type': value['sportType'],
        'intensity': value['intensity'],
        'venue_ids': value['venueIds'],
        'price_min': value['priceMin'],
        'price_max': value['priceMax'],
        'currency': value['currency'],
        'status': value['status'],
        'created_at': value['createdAt'].toISOString(),
        'matched_events': ((value['matchedEvents'] as Array<any>).map(MatchedEventSummaryToJSON)),
    };
}

