/* tslint:disable */
/* eslint-disable */
/**
 * TeamUp API
 * Sports venue booking and team formation API  Features: - Venue search with geolocation - Timeslot booking - TeamUp creation and management - Join request workflow 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateUserInfoRequest
 */
export interface UpdateUserInfoRequest {
    /**
     * 
     * @type {string}
     * @memberof UpdateUserInfoRequest
     */
    displayName?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof UpdateUserInfoRequest
     */
    preferredSports?: Array<string> | null;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof UpdateUserInfoRequest
     */
    skillLevels?: { [key: string]: string; } | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof UpdateUserInfoRequest
     */
    preferredTimeSlots?: Array<string> | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateUserInfoRequest
     */
    preferredLanguage?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateUserInfoRequest
     */
    customPreferences?: string | null;
}

/**
 * Check if a given object implements the UpdateUserInfoRequest interface.
 */
export function instanceOfUpdateUserInfoRequest(value: object): value is UpdateUserInfoRequest {
    return true;
}

export function UpdateUserInfoRequestFromJSON(json: any): UpdateUserInfoRequest {
    return UpdateUserInfoRequestFromJSONTyped(json, false);
}

export function UpdateUserInfoRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateUserInfoRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'displayName': json['display_name'] == null ? undefined : json['display_name'],
        'preferredSports': json['preferred_sports'] == null ? undefined : json['preferred_sports'],
        'skillLevels': json['skill_levels'] == null ? undefined : json['skill_levels'],
        'preferredTimeSlots': json['preferred_time_slots'] == null ? undefined : json['preferred_time_slots'],
        'preferredLanguage': json['preferred_language'] == null ? undefined : json['preferred_language'],
        'customPreferences': json['custom_preferences'] == null ? undefined : json['custom_preferences'],
    };
}

export function UpdateUserInfoRequestToJSON(json: any): UpdateUserInfoRequest {
    return UpdateUserInfoRequestToJSONTyped(json, false);
}

export function UpdateUserInfoRequestToJSONTyped(value?: UpdateUserInfoRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'display_name': value['displayName'],
        'preferred_sports': value['preferredSports'],
        'skill_levels': value['skillLevels'],
        'preferred_time_slots': value['preferredTimeSlots'],
        'preferred_language': value['preferredLanguage'],
        'custom_preferences': value['customPreferences'],
    };
}

