/* tslint:disable */
/* eslint-disable */
/**
 * TeamUp API
 * Sports venue booking and team formation API  Features: - Venue search with geolocation - Timeslot booking - TeamUp creation and management - Join request workflow 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserOut
 */
export interface UserOut {
    /**
     * 
     * @type {string}
     * @memberof UserOut
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof UserOut
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof UserOut
     */
    displayName: string | null;
    /**
     * 
     * @type {Date}
     * @memberof UserOut
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof UserOut
     */
    updatedAt: Date;
    /**
     * 
     * @type {Array<string>}
     * @memberof UserOut
     */
    preferredSports?: Array<string> | null;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof UserOut
     */
    skillLevels?: { [key: string]: string; } | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof UserOut
     */
    preferredTimeSlots?: Array<string> | null;
    /**
     * 
     * @type {string}
     * @memberof UserOut
     */
    preferredLanguage?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserOut
     */
    customPreferences?: string | null;
}

/**
 * Check if a given object implements the UserOut interface.
 */
export function instanceOfUserOut(value: object): value is UserOut {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('displayName' in value) || value['displayName'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function UserOutFromJSON(json: any): UserOut {
    return UserOutFromJSONTyped(json, false);
}

export function UserOutFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserOut {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'email': json['email'],
        'displayName': json['display_name'],
        'createdAt': (new Date(json['created_at'])),
        'updatedAt': (new Date(json['updated_at'])),
        'preferredSports': json['preferred_sports'] == null ? undefined : json['preferred_sports'],
        'skillLevels': json['skill_levels'] == null ? undefined : json['skill_levels'],
        'preferredTimeSlots': json['preferred_time_slots'] == null ? undefined : json['preferred_time_slots'],
        'preferredLanguage': json['preferred_language'] == null ? undefined : json['preferred_language'],
        'customPreferences': json['custom_preferences'] == null ? undefined : json['custom_preferences'],
    };
}

export function UserOutToJSON(json: any): UserOut {
    return UserOutToJSONTyped(json, false);
}

export function UserOutToJSONTyped(value?: UserOut | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'email': value['email'],
        'display_name': value['displayName'],
        'created_at': value['createdAt'].toISOString(),
        'updated_at': value['updatedAt'].toISOString(),
        'preferred_sports': value['preferredSports'],
        'skill_levels': value['skillLevels'],
        'preferred_time_slots': value['preferredTimeSlots'],
        'preferred_language': value['preferredLanguage'],
        'custom_preferences': value['customPreferences'],
    };
}

