/* tslint:disable */
/* eslint-disable */
/**
 * TeamUp API
 * Sports venue booking and team formation API  Features: - Venue search with geolocation - Timeslot booking - TeamUp creation and management - Join request workflow 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CourtOut } from './CourtOut';
import {
    CourtOutFromJSON,
    CourtOutFromJSONTyped,
    CourtOutToJSON,
    CourtOutToJSONTyped,
} from './CourtOut';

/**
 * 
 * @export
 * @interface VenueDetail
 */
export interface VenueDetail {
    /**
     * 
     * @type {string}
     * @memberof VenueDetail
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof VenueDetail
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof VenueDetail
     */
    address: string;
    /**
     * 
     * @type {string}
     * @memberof VenueDetail
     */
    city?: string | null;
    /**
     * 
     * @type {number}
     * @memberof VenueDetail
     */
    latitude?: number | null;
    /**
     * 
     * @type {number}
     * @memberof VenueDetail
     */
    longitude?: number | null;
    /**
     * 
     * @type {string}
     * @memberof VenueDetail
     */
    contactPhone?: string | null;
    /**
     * 
     * @type {string}
     * @memberof VenueDetail
     */
    partnerCode?: string | null;
    /**
     * 
     * @type {Array<CourtOut>}
     * @memberof VenueDetail
     */
    courts: Array<CourtOut>;
    /**
     * 
     * @type {Date}
     * @memberof VenueDetail
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof VenueDetail
     */
    updatedAt: Date;
}

/**
 * Check if a given object implements the VenueDetail interface.
 */
export function instanceOfVenueDetail(value: object): value is VenueDetail {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('address' in value) || value['address'] === undefined) return false;
    if (!('courts' in value) || value['courts'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function VenueDetailFromJSON(json: any): VenueDetail {
    return VenueDetailFromJSONTyped(json, false);
}

export function VenueDetailFromJSONTyped(json: any, ignoreDiscriminator: boolean): VenueDetail {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'address': json['address'],
        'city': json['city'] == null ? undefined : json['city'],
        'latitude': json['latitude'] == null ? undefined : json['latitude'],
        'longitude': json['longitude'] == null ? undefined : json['longitude'],
        'contactPhone': json['contact_phone'] == null ? undefined : json['contact_phone'],
        'partnerCode': json['partner_code'] == null ? undefined : json['partner_code'],
        'courts': ((json['courts'] as Array<any>).map(CourtOutFromJSON)),
        'createdAt': (new Date(json['created_at'])),
        'updatedAt': (new Date(json['updated_at'])),
    };
}

export function VenueDetailToJSON(json: any): VenueDetail {
    return VenueDetailToJSONTyped(json, false);
}

export function VenueDetailToJSONTyped(value?: VenueDetail | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'address': value['address'],
        'city': value['city'],
        'latitude': value['latitude'],
        'longitude': value['longitude'],
        'contact_phone': value['contactPhone'],
        'partner_code': value['partnerCode'],
        'courts': ((value['courts'] as Array<any>).map(CourtOutToJSON)),
        'created_at': value['createdAt'].toISOString(),
        'updated_at': value['updatedAt'].toISOString(),
    };
}

