/* tslint:disable */
/* eslint-disable */
/**
 * TeamUp API
 * Sports venue booking and team formation API  Features: - Venue search with geolocation - Timeslot booking - TeamUp creation and management - Join request workflow 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VenueUpdateIn
 */
export interface VenueUpdateIn {
    /**
     * 
     * @type {string}
     * @memberof VenueUpdateIn
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof VenueUpdateIn
     */
    address?: string;
    /**
     * 
     * @type {string}
     * @memberof VenueUpdateIn
     */
    city?: string | null;
    /**
     * 
     * @type {number}
     * @memberof VenueUpdateIn
     */
    latitude?: number | null;
    /**
     * 
     * @type {number}
     * @memberof VenueUpdateIn
     */
    longitude?: number | null;
    /**
     * 
     * @type {string}
     * @memberof VenueUpdateIn
     */
    contactPhone?: string | null;
    /**
     * 
     * @type {string}
     * @memberof VenueUpdateIn
     */
    partnerCode?: string | null;
}

/**
 * Check if a given object implements the VenueUpdateIn interface.
 */
export function instanceOfVenueUpdateIn(value: object): value is VenueUpdateIn {
    return true;
}

export function VenueUpdateInFromJSON(json: any): VenueUpdateIn {
    return VenueUpdateInFromJSONTyped(json, false);
}

export function VenueUpdateInFromJSONTyped(json: any, ignoreDiscriminator: boolean): VenueUpdateIn {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'address': json['address'] == null ? undefined : json['address'],
        'city': json['city'] == null ? undefined : json['city'],
        'latitude': json['latitude'] == null ? undefined : json['latitude'],
        'longitude': json['longitude'] == null ? undefined : json['longitude'],
        'contactPhone': json['contact_phone'] == null ? undefined : json['contact_phone'],
        'partnerCode': json['partner_code'] == null ? undefined : json['partner_code'],
    };
}

export function VenueUpdateInToJSON(json: any): VenueUpdateIn {
    return VenueUpdateInToJSONTyped(json, false);
}

export function VenueUpdateInToJSONTyped(value?: VenueUpdateIn | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'address': value['address'],
        'city': value['city'],
        'latitude': value['latitude'],
        'longitude': value['longitude'],
        'contact_phone': value['contactPhone'],
        'partner_code': value['partnerCode'],
    };
}

