#!/bin/bash

echo "=== Railway Configuration Check ==="
echo ""

echo "1. Current environment variables:"
railway variables 2>&1 | grep -E "(DATABASE_URL|JWT_SECRET|BOOTSTRAP_DB)" || echo "   No relevant variables found"
echo ""

echo "2. Available services in project:"
railway service list 2>&1 || echo "   Could not list services"
echo ""

echo "=== Instructions to Fix Database Connection ==="
echo ""
echo "Your API is deployed but can't connect to Postgres."
echo "You need to link the services in Railway Dashboard:"
echo ""
echo "METHOD 1: Railway Dashboard (Easiest)"
echo "  1. Go to: https://railway.app"
echo "  2. Select your project"
echo "  3. Click on your API service (NOT Postgres)"
echo "  4. Click 'Variables' tab"
echo "  5. Click '+ New Variable' → 'Add Reference'"
echo "  6. Select 'Postgres' service"
echo "  7. Check 'DATABASE_URL'"
echo "  8. Click 'Add'"
echo "  9. Wait for automatic redeploy (~2 minutes)"
echo ""
echo "METHOD 2: Generate Public URL for Postgres (Alternative, less secure)"
echo "  1. Click on Postgres service"
echo "  2. Settings → Networking"
echo "  3. Generate Domain (this makes it publicly accessible)"
echo "  4. Copy the DATABASE_URL from Variables"
echo "  5. Go to API service → Variables"
echo "  6. Set DATABASE_URL to the public URL"
echo ""
echo "After fixing, verify with:"
echo "  railway logs"
echo ""
echo "You should see: 'Database tables initialized successfully'"
