#!/bin/bash

echo "=== Fixing Railway Database Connection ==="
echo ""

# The public DATABASE_URL from your Postgres service
PUBLIC_DB_URL="postgresql://postgres:ISANfSALVDpgBEumMhfwKRGMslMIvZux@yamabiko.proxy.rlwy.net:25484/railway"

echo "Current issue:"
echo "  - You're linked to the Postgres service"
echo "  - You need to set DATABASE_URL for your API service"
echo ""
echo "Solution: Use the PUBLIC database URL temporarily"
echo ""
echo "The DATABASE_URL to use:"
echo "  $PUBLIC_DB_URL"
echo ""
echo "=== MANUAL STEPS REQUIRED ==="
echo ""
echo "Since Railway CLI can't switch services non-interactively,"
echo "you need to do this via the Railway Dashboard:"
echo ""
echo "1. Go to: https://railway.app/project/2c11e499-7ab9-4985-8ad4-509825388eb0"
echo ""
echo "2. Click on your API service (the one with Docker builds, NOT Postgres)"
echo ""
echo "3. Click 'Variables' tab"
echo ""
echo "4. Find DATABASE_URL and click to edit it"
echo ""
echo "5. Paste this value:"
echo "   postgresql://postgres:ISANfSALVDpgBEumMhfwKRGMslMIvZux@yamabiko.proxy.rlwy.net:25484/railway"
echo ""
echo "6. Save and wait for automatic redeploy"
echo ""
echo "=== OR: Use railway CLI interactively ==="
echo ""
echo "Run these commands in your terminal:"
echo ""
echo "  cd services/api"
echo "  railway link    # Select your API service (NOT Postgres)"
echo "  railway variables set DATABASE_URL=\"$PUBLIC_DB_URL\""
echo ""
echo "=== Verify after fixing ==="
echo ""
echo "  railway logs"
echo ""
echo "Look for: 'Database tables initialized successfully'"
echo ""
