/* tslint:disable */
/* eslint-disable */
/**
 * TeamUp API
 * Sports venue booking and team formation API  Features: - Venue search with geolocation - Timeslot booking - TeamUp creation and management - Join request workflow 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  BookingCreateIn,
  BookingDetailOut,
  BookingOut,
  BookingUpdateIn,
  DeleteAccount200Response,
} from '../models/index';
import {
    BookingCreateInFromJSON,
    BookingCreateInToJSON,
    BookingDetailOutFromJSON,
    BookingDetailOutToJSON,
    BookingOutFromJSON,
    BookingOutToJSON,
    BookingUpdateInFromJSON,
    BookingUpdateInToJSON,
    DeleteAccount200ResponseFromJSON,
    DeleteAccount200ResponseToJSON,
} from '../models/index';

export interface CancelBookingRequest {
    bookingId: string;
}

export interface CreateBookingRequest {
    bookingCreateIn: BookingCreateIn;
}

export interface GetBookingByIdRequest {
    bookingId: string;
}

export interface ListBookingsRequest {
    status?: ListBookingsStatusEnum;
    limit?: number;
    offset?: number;
}

export interface UpdateBookingRequest {
    bookingId: string;
    bookingUpdateIn: BookingUpdateIn;
}

export interface UpdateBookingFullyRequest {
    bookingId: string;
    bookingUpdateIn: BookingUpdateIn;
}

/**
 * 
 */
export class BookingsApi extends runtime.BaseAPI {

    /**
     * Cancel booking
     */
    async cancelBookingRaw(requestParameters: CancelBookingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DeleteAccount200Response>> {
        if (requestParameters['bookingId'] == null) {
            throw new runtime.RequiredError(
                'bookingId',
                'Required parameter "bookingId" was null or undefined when calling cancelBooking().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/bookings/{booking_id}`;
        urlPath = urlPath.replace(`{${"booking_id"}}`, encodeURIComponent(String(requestParameters['bookingId'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DeleteAccount200ResponseFromJSON(jsonValue));
    }

    /**
     * Cancel booking
     */
    async cancelBooking(requestParameters: CancelBookingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DeleteAccount200Response> {
        const response = await this.cancelBookingRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Create a new booking
     */
    async createBookingRaw(requestParameters: CreateBookingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BookingOut>> {
        if (requestParameters['bookingCreateIn'] == null) {
            throw new runtime.RequiredError(
                'bookingCreateIn',
                'Required parameter "bookingCreateIn" was null or undefined when calling createBooking().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/bookings`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: BookingCreateInToJSON(requestParameters['bookingCreateIn']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BookingOutFromJSON(jsonValue));
    }

    /**
     * Create a new booking
     */
    async createBooking(requestParameters: CreateBookingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BookingOut> {
        const response = await this.createBookingRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get booking details
     */
    async getBookingByIdRaw(requestParameters: GetBookingByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BookingDetailOut>> {
        if (requestParameters['bookingId'] == null) {
            throw new runtime.RequiredError(
                'bookingId',
                'Required parameter "bookingId" was null or undefined when calling getBookingById().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/bookings/{booking_id}`;
        urlPath = urlPath.replace(`{${"booking_id"}}`, encodeURIComponent(String(requestParameters['bookingId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BookingDetailOutFromJSON(jsonValue));
    }

    /**
     * Get booking details
     */
    async getBookingById(requestParameters: GetBookingByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BookingDetailOut> {
        const response = await this.getBookingByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List user\'s bookings
     */
    async listBookingsRaw(requestParameters: ListBookingsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<BookingOut>>> {
        const queryParameters: any = {};

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/bookings`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(BookingOutFromJSON));
    }

    /**
     * List user\'s bookings
     */
    async listBookings(requestParameters: ListBookingsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<BookingOut>> {
        const response = await this.listBookingsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update booking status
     */
    async updateBookingRaw(requestParameters: UpdateBookingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BookingOut>> {
        if (requestParameters['bookingId'] == null) {
            throw new runtime.RequiredError(
                'bookingId',
                'Required parameter "bookingId" was null or undefined when calling updateBooking().'
            );
        }

        if (requestParameters['bookingUpdateIn'] == null) {
            throw new runtime.RequiredError(
                'bookingUpdateIn',
                'Required parameter "bookingUpdateIn" was null or undefined when calling updateBooking().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/bookings/{booking_id}`;
        urlPath = urlPath.replace(`{${"booking_id"}}`, encodeURIComponent(String(requestParameters['bookingId'])));

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: BookingUpdateInToJSON(requestParameters['bookingUpdateIn']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BookingOutFromJSON(jsonValue));
    }

    /**
     * Update booking status
     */
    async updateBooking(requestParameters: UpdateBookingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BookingOut> {
        const response = await this.updateBookingRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update booking fully (admin)
     */
    async updateBookingFullyRaw(requestParameters: UpdateBookingFullyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BookingOut>> {
        if (requestParameters['bookingId'] == null) {
            throw new runtime.RequiredError(
                'bookingId',
                'Required parameter "bookingId" was null or undefined when calling updateBookingFully().'
            );
        }

        if (requestParameters['bookingUpdateIn'] == null) {
            throw new runtime.RequiredError(
                'bookingUpdateIn',
                'Required parameter "bookingUpdateIn" was null or undefined when calling updateBookingFully().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/bookings/{booking_id}`;
        urlPath = urlPath.replace(`{${"booking_id"}}`, encodeURIComponent(String(requestParameters['bookingId'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: BookingUpdateInToJSON(requestParameters['bookingUpdateIn']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BookingOutFromJSON(jsonValue));
    }

    /**
     * Update booking fully (admin)
     */
    async updateBookingFully(requestParameters: UpdateBookingFullyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BookingOut> {
        const response = await this.updateBookingFullyRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const ListBookingsStatusEnum = {
    pending: 'pending',
    confirmed: 'confirmed',
    cancelled: 'cancelled'
} as const;
export type ListBookingsStatusEnum = typeof ListBookingsStatusEnum[keyof typeof ListBookingsStatusEnum];
