/* tslint:disable */
/* eslint-disable */
/**
 * TeamUp API
 * Sports venue booking and team formation API  Features: - Venue search with geolocation - Timeslot booking - TeamUp creation and management - Join request workflow 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ChatMessageIn,
  ChatMessageOut,
  DeleteAccount200Response,
} from '../models/index';
import {
    ChatMessageInFromJSON,
    ChatMessageInToJSON,
    ChatMessageOutFromJSON,
    ChatMessageOutToJSON,
    DeleteAccount200ResponseFromJSON,
    DeleteAccount200ResponseToJSON,
} from '../models/index';

export interface ListMessagesRequest {
    limit?: number;
    cursor?: string;
}

export interface PostMessageRequest {
    chatMessageIn: ChatMessageIn;
}

/**
 * 
 */
export class ChatApi extends runtime.BaseAPI {

    /**
     * Clear chat history
     */
    async clearMessagesRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DeleteAccount200Response>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/chat/messages`;

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DeleteAccount200ResponseFromJSON(jsonValue));
    }

    /**
     * Clear chat history
     */
    async clearMessages(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DeleteAccount200Response> {
        const response = await this.clearMessagesRaw(initOverrides);
        return await response.value();
    }

    /**
     * List chat messages
     */
    async listMessagesRaw(requestParameters: ListMessagesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ChatMessageOut>>> {
        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['cursor'] != null) {
            queryParameters['cursor'] = requestParameters['cursor'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/chat/messages`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ChatMessageOutFromJSON));
    }

    /**
     * List chat messages
     */
    async listMessages(requestParameters: ListMessagesRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ChatMessageOut>> {
        const response = await this.listMessagesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Send a chat message
     */
    async postMessageRaw(requestParameters: PostMessageRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ChatMessageOut>> {
        if (requestParameters['chatMessageIn'] == null) {
            throw new runtime.RequiredError(
                'chatMessageIn',
                'Required parameter "chatMessageIn" was null or undefined when calling postMessage().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/chat/messages`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ChatMessageInToJSON(requestParameters['chatMessageIn']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ChatMessageOutFromJSON(jsonValue));
    }

    /**
     * Send a chat message
     */
    async postMessage(requestParameters: PostMessageRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ChatMessageOut> {
        const response = await this.postMessageRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
