/* tslint:disable */
/* eslint-disable */
/**
 * TeamUp API
 * Sports venue booking and team formation API  Features: - Venue search with geolocation - Timeslot booking - TeamUp creation and management - Join request workflow 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  DeleteAccount200Response,
  EventBookTimeSlotIn,
  EventBookingDetail,
  EventBookingResponse,
  EventCreateIn,
  EventDetailOut,
  EventOut,
  EventUpdateIn,
  JoinRequestCreateIn,
  JoinRequestOut,
  JoinRequestReviewIn,
  JoinRequestReviewResponse,
  JoinRequestSubmitResponse,
} from '../models/index';
import {
    DeleteAccount200ResponseFromJSON,
    DeleteAccount200ResponseToJSON,
    EventBookTimeSlotInFromJSON,
    EventBookTimeSlotInToJSON,
    EventBookingDetailFromJSON,
    EventBookingDetailToJSON,
    EventBookingResponseFromJSON,
    EventBookingResponseToJSON,
    EventCreateInFromJSON,
    EventCreateInToJSON,
    EventDetailOutFromJSON,
    EventDetailOutToJSON,
    EventOutFromJSON,
    EventOutToJSON,
    EventUpdateInFromJSON,
    EventUpdateInToJSON,
    JoinRequestCreateInFromJSON,
    JoinRequestCreateInToJSON,
    JoinRequestOutFromJSON,
    JoinRequestOutToJSON,
    JoinRequestReviewInFromJSON,
    JoinRequestReviewInToJSON,
    JoinRequestReviewResponseFromJSON,
    JoinRequestReviewResponseToJSON,
    JoinRequestSubmitResponseFromJSON,
    JoinRequestSubmitResponseToJSON,
} from '../models/index';

export interface BookTimeslotForEventRequest {
    eventId: string;
    eventBookTimeSlotIn: EventBookTimeSlotIn;
}

export interface CreateEventRequest {
    eventCreateIn: EventCreateIn;
}

export interface DeleteEventRequest {
    eventId: string;
}

export interface GetEventByIdRequest {
    eventId: string;
}

export interface JoinEventRequest {
    eventId: string;
    joinRequestCreateIn?: JoinRequestCreateIn;
}

export interface ListEventBookingsRequest {
    eventId: string;
}

export interface ListEventsRequest {
    status?: ListEventsStatusEnum;
    visibility?: ListEventsVisibilityEnum;
    keyword?: string;
    datetimeAfter?: Date;
    division?: string;
    category?: string;
    limit?: number;
    offset?: number;
}

export interface ListJoinRequestsRequest {
    eventId: string;
}

export interface ReviewJoinRequestRequest {
    eventId: string;
    requestId: string;
    joinRequestReviewIn: JoinRequestReviewIn;
}

export interface UpdateEventRequest {
    eventId: string;
    eventUpdateIn: EventUpdateIn;
}

/**
 * 
 */
export class EventsApi extends runtime.BaseAPI {

    /**
     * Creates request options for bookTimeslotForEvent without sending the request
     */
    async bookTimeslotForEventRequestOpts(requestParameters: BookTimeslotForEventRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['eventId'] == null) {
            throw new runtime.RequiredError(
                'eventId',
                'Required parameter "eventId" was null or undefined when calling bookTimeslotForEvent().'
            );
        }

        if (requestParameters['eventBookTimeSlotIn'] == null) {
            throw new runtime.RequiredError(
                'eventBookTimeSlotIn',
                'Required parameter "eventBookTimeSlotIn" was null or undefined when calling bookTimeslotForEvent().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/events/{event_id}/book`;
        urlPath = urlPath.replace(`{${"event_id"}}`, encodeURIComponent(String(requestParameters['eventId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: EventBookTimeSlotInToJSON(requestParameters['eventBookTimeSlotIn']),
        };
    }

    /**
     * Event owner can book multiple time slots for the team
     * Book a timeslot for Event (owner only)
     */
    async bookTimeslotForEventRaw(requestParameters: BookTimeslotForEventRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EventBookingResponse>> {
        const requestOptions = await this.bookTimeslotForEventRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EventBookingResponseFromJSON(jsonValue));
    }

    /**
     * Event owner can book multiple time slots for the team
     * Book a timeslot for Event (owner only)
     */
    async bookTimeslotForEvent(requestParameters: BookTimeslotForEventRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EventBookingResponse> {
        const response = await this.bookTimeslotForEventRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for createEvent without sending the request
     */
    async createEventRequestOpts(requestParameters: CreateEventRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['eventCreateIn'] == null) {
            throw new runtime.RequiredError(
                'eventCreateIn',
                'Required parameter "eventCreateIn" was null or undefined when calling createEvent().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/events`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: EventCreateInToJSON(requestParameters['eventCreateIn']),
        };
    }

    /**
     * Create a new Event
     */
    async createEventRaw(requestParameters: CreateEventRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EventOut>> {
        const requestOptions = await this.createEventRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EventOutFromJSON(jsonValue));
    }

    /**
     * Create a new Event
     */
    async createEvent(requestParameters: CreateEventRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EventOut> {
        const response = await this.createEventRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deleteEvent without sending the request
     */
    async deleteEventRequestOpts(requestParameters: DeleteEventRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['eventId'] == null) {
            throw new runtime.RequiredError(
                'eventId',
                'Required parameter "eventId" was null or undefined when calling deleteEvent().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/events/{event_id}`;
        urlPath = urlPath.replace(`{${"event_id"}}`, encodeURIComponent(String(requestParameters['eventId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Delete Event
     */
    async deleteEventRaw(requestParameters: DeleteEventRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DeleteAccount200Response>> {
        const requestOptions = await this.deleteEventRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DeleteAccount200ResponseFromJSON(jsonValue));
    }

    /**
     * Delete Event
     */
    async deleteEvent(requestParameters: DeleteEventRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DeleteAccount200Response> {
        const response = await this.deleteEventRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getEventById without sending the request
     */
    async getEventByIdRequestOpts(requestParameters: GetEventByIdRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['eventId'] == null) {
            throw new runtime.RequiredError(
                'eventId',
                'Required parameter "eventId" was null or undefined when calling getEventById().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/events/{event_id}`;
        urlPath = urlPath.replace(`{${"event_id"}}`, encodeURIComponent(String(requestParameters['eventId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get Event details
     */
    async getEventByIdRaw(requestParameters: GetEventByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EventDetailOut>> {
        const requestOptions = await this.getEventByIdRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EventDetailOutFromJSON(jsonValue));
    }

    /**
     * Get Event details
     */
    async getEventById(requestParameters: GetEventByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EventDetailOut> {
        const response = await this.getEventByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getMyCreatedEvents without sending the request
     */
    async getMyCreatedEventsRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/events/my/created`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns all events owned by the authenticated user
     * Get events created by the authenticated user
     */
    async getMyCreatedEventsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<EventOut>>> {
        const requestOptions = await this.getMyCreatedEventsRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(EventOutFromJSON));
    }

    /**
     * Returns all events owned by the authenticated user
     * Get events created by the authenticated user
     */
    async getMyCreatedEvents(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<EventOut>> {
        const response = await this.getMyCreatedEventsRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getMyJoinedEvents without sending the request
     */
    async getMyJoinedEventsRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/events/my/joined`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns all events where the authenticated user is a participant (member role)
     * Get events joined by the authenticated user
     */
    async getMyJoinedEventsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<EventOut>>> {
        const requestOptions = await this.getMyJoinedEventsRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(EventOutFromJSON));
    }

    /**
     * Returns all events where the authenticated user is a participant (member role)
     * Get events joined by the authenticated user
     */
    async getMyJoinedEvents(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<EventOut>> {
        const response = await this.getMyJoinedEventsRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getMyPendingEvents without sending the request
     */
    async getMyPendingEventsRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/events/my/pending`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns all events where the authenticated user has submitted join requests
     * Get events with pending join requests
     */
    async getMyPendingEventsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<EventOut>>> {
        const requestOptions = await this.getMyPendingEventsRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(EventOutFromJSON));
    }

    /**
     * Returns all events where the authenticated user has submitted join requests
     * Get events with pending join requests
     */
    async getMyPendingEvents(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<EventOut>> {
        const response = await this.getMyPendingEventsRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for joinEvent without sending the request
     */
    async joinEventRequestOpts(requestParameters: JoinEventRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['eventId'] == null) {
            throw new runtime.RequiredError(
                'eventId',
                'Required parameter "eventId" was null or undefined when calling joinEvent().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/events/{event_id}/join`;
        urlPath = urlPath.replace(`{${"event_id"}}`, encodeURIComponent(String(requestParameters['eventId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: JoinRequestCreateInToJSON(requestParameters['joinRequestCreateIn']),
        };
    }

    /**
     * Submit a join request to join a Event. Authenticated users auto-fill their info, non-authenticated users must provide details. 
     * Submit join request to Event
     */
    async joinEventRaw(requestParameters: JoinEventRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<JoinRequestSubmitResponse>> {
        const requestOptions = await this.joinEventRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => JoinRequestSubmitResponseFromJSON(jsonValue));
    }

    /**
     * Submit a join request to join a Event. Authenticated users auto-fill their info, non-authenticated users must provide details. 
     * Submit join request to Event
     */
    async joinEvent(requestParameters: JoinEventRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<JoinRequestSubmitResponse> {
        const response = await this.joinEventRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listEventBookings without sending the request
     */
    async listEventBookingsRequestOpts(requestParameters: ListEventBookingsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['eventId'] == null) {
            throw new runtime.RequiredError(
                'eventId',
                'Required parameter "eventId" was null or undefined when calling listEventBookings().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/events/{event_id}/bookings`;
        urlPath = urlPath.replace(`{${"event_id"}}`, encodeURIComponent(String(requestParameters['eventId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List all bookings for a Event
     */
    async listEventBookingsRaw(requestParameters: ListEventBookingsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<EventBookingDetail>>> {
        const requestOptions = await this.listEventBookingsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(EventBookingDetailFromJSON));
    }

    /**
     * List all bookings for a Event
     */
    async listEventBookings(requestParameters: ListEventBookingsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<EventBookingDetail>> {
        const response = await this.listEventBookingsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listEvents without sending the request
     */
    async listEventsRequestOpts(requestParameters: ListEventsRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        if (requestParameters['visibility'] != null) {
            queryParameters['visibility'] = requestParameters['visibility'];
        }

        if (requestParameters['keyword'] != null) {
            queryParameters['keyword'] = requestParameters['keyword'];
        }

        if (requestParameters['datetimeAfter'] != null) {
            queryParameters['datetime_after'] = (requestParameters['datetimeAfter'] as any).toISOString();
        }

        if (requestParameters['division'] != null) {
            queryParameters['division'] = requestParameters['division'];
        }

        if (requestParameters['category'] != null) {
            queryParameters['category'] = requestParameters['category'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/events`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List Events with optional filtering and search. Supports filtering by status, visibility, and keyword search on title. 
     * List and search Events
     */
    async listEventsRaw(requestParameters: ListEventsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<EventOut>>> {
        const requestOptions = await this.listEventsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(EventOutFromJSON));
    }

    /**
     * List Events with optional filtering and search. Supports filtering by status, visibility, and keyword search on title. 
     * List and search Events
     */
    async listEvents(requestParameters: ListEventsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<EventOut>> {
        const response = await this.listEventsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listJoinRequests without sending the request
     */
    async listJoinRequestsRequestOpts(requestParameters: ListJoinRequestsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['eventId'] == null) {
            throw new runtime.RequiredError(
                'eventId',
                'Required parameter "eventId" was null or undefined when calling listJoinRequests().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/events/{event_id}/join-requests`;
        urlPath = urlPath.replace(`{${"event_id"}}`, encodeURIComponent(String(requestParameters['eventId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List join requests (owner only)
     */
    async listJoinRequestsRaw(requestParameters: ListJoinRequestsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<JoinRequestOut>>> {
        const requestOptions = await this.listJoinRequestsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(JoinRequestOutFromJSON));
    }

    /**
     * List join requests (owner only)
     */
    async listJoinRequests(requestParameters: ListJoinRequestsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<JoinRequestOut>> {
        const response = await this.listJoinRequestsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for reviewJoinRequest without sending the request
     */
    async reviewJoinRequestRequestOpts(requestParameters: ReviewJoinRequestRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['eventId'] == null) {
            throw new runtime.RequiredError(
                'eventId',
                'Required parameter "eventId" was null or undefined when calling reviewJoinRequest().'
            );
        }

        if (requestParameters['requestId'] == null) {
            throw new runtime.RequiredError(
                'requestId',
                'Required parameter "requestId" was null or undefined when calling reviewJoinRequest().'
            );
        }

        if (requestParameters['joinRequestReviewIn'] == null) {
            throw new runtime.RequiredError(
                'joinRequestReviewIn',
                'Required parameter "joinRequestReviewIn" was null or undefined when calling reviewJoinRequest().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/events/{event_id}/join-requests/{request_id}/review`;
        urlPath = urlPath.replace(`{${"event_id"}}`, encodeURIComponent(String(requestParameters['eventId'])));
        urlPath = urlPath.replace(`{${"request_id"}}`, encodeURIComponent(String(requestParameters['requestId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: JoinRequestReviewInToJSON(requestParameters['joinRequestReviewIn']),
        };
    }

    /**
     * Approve or reject a join request
     * Review join request (owner only)
     */
    async reviewJoinRequestRaw(requestParameters: ReviewJoinRequestRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<JoinRequestReviewResponse>> {
        const requestOptions = await this.reviewJoinRequestRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => JoinRequestReviewResponseFromJSON(jsonValue));
    }

    /**
     * Approve or reject a join request
     * Review join request (owner only)
     */
    async reviewJoinRequest(requestParameters: ReviewJoinRequestRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<JoinRequestReviewResponse> {
        const response = await this.reviewJoinRequestRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateEvent without sending the request
     */
    async updateEventRequestOpts(requestParameters: UpdateEventRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['eventId'] == null) {
            throw new runtime.RequiredError(
                'eventId',
                'Required parameter "eventId" was null or undefined when calling updateEvent().'
            );
        }

        if (requestParameters['eventUpdateIn'] == null) {
            throw new runtime.RequiredError(
                'eventUpdateIn',
                'Required parameter "eventUpdateIn" was null or undefined when calling updateEvent().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/events/{event_id}`;
        urlPath = urlPath.replace(`{${"event_id"}}`, encodeURIComponent(String(requestParameters['eventId'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: EventUpdateInToJSON(requestParameters['eventUpdateIn']),
        };
    }

    /**
     * Update Event
     */
    async updateEventRaw(requestParameters: UpdateEventRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EventDetailOut>> {
        const requestOptions = await this.updateEventRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EventDetailOutFromJSON(jsonValue));
    }

    /**
     * Update Event
     */
    async updateEvent(requestParameters: UpdateEventRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EventDetailOut> {
        const response = await this.updateEventRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const ListEventsStatusEnum = {
    Open: 'open',
    Closed: 'closed'
} as const;
export type ListEventsStatusEnum = typeof ListEventsStatusEnum[keyof typeof ListEventsStatusEnum];
/**
 * @export
 */
export const ListEventsVisibilityEnum = {
    Public: 'public',
    Private: 'private'
} as const;
export type ListEventsVisibilityEnum = typeof ListEventsVisibilityEnum[keyof typeof ListEventsVisibilityEnum];
