/* tslint:disable */
/* eslint-disable */
/**
 * TeamUp API
 * Sports venue booking and team formation API  Features: - Venue search with geolocation - Timeslot booking - TeamUp creation and management - Join request workflow 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  BookingOut,
  EventOut,
  JoinRequestOut,
  UpdateUserInfoRequest,
  UserOut,
} from '../models/index';
import {
    BookingOutFromJSON,
    BookingOutToJSON,
    EventOutFromJSON,
    EventOutToJSON,
    JoinRequestOutFromJSON,
    JoinRequestOutToJSON,
    UpdateUserInfoRequestFromJSON,
    UpdateUserInfoRequestToJSON,
    UserOutFromJSON,
    UserOutToJSON,
} from '../models/index';

export interface CancelUserJoinRequestRequest {
    joinRequestId: string;
}

export interface GetUserJoinRequestRequest {
    joinRequestId: string;
}

export interface UpdateUserInfoOperationRequest {
    updateUserInfoRequest?: UpdateUserInfoRequest;
}

/**
 * 
 */
export class UserApi extends runtime.BaseAPI {

    /**
     * Creates request options for cancelUserJoinRequest without sending the request
     */
    async cancelUserJoinRequestRequestOpts(requestParameters: CancelUserJoinRequestRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['joinRequestId'] == null) {
            throw new runtime.RequiredError(
                'joinRequestId',
                'Required parameter "joinRequestId" was null or undefined when calling cancelUserJoinRequest().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/user/events/join_requests/{join_request_id}`;
        urlPath = urlPath.replace(`{${"join_request_id"}}`, encodeURIComponent(String(requestParameters['joinRequestId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Cancel join request
     */
    async cancelUserJoinRequestRaw(requestParameters: CancelUserJoinRequestRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.cancelUserJoinRequestRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Cancel join request
     */
    async cancelUserJoinRequest(requestParameters: CancelUserJoinRequestRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.cancelUserJoinRequestRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for getUserBookings without sending the request
     */
    async getUserBookingsRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/user/bookings`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get user bookings
     */
    async getUserBookingsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<BookingOut>>> {
        const requestOptions = await this.getUserBookingsRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(BookingOutFromJSON));
    }

    /**
     * Get user bookings
     */
    async getUserBookings(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<BookingOut>> {
        const response = await this.getUserBookingsRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getUserEvents without sending the request
     */
    async getUserEventsRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/user/events`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get user events (created, joined, requested)
     */
    async getUserEventsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<EventOut>>> {
        const requestOptions = await this.getUserEventsRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(EventOutFromJSON));
    }

    /**
     * Get user events (created, joined, requested)
     */
    async getUserEvents(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<EventOut>> {
        const response = await this.getUserEventsRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getUserInfo without sending the request
     */
    async getUserInfoRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/user/info`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get user info
     */
    async getUserInfoRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserOut>> {
        const requestOptions = await this.getUserInfoRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserOutFromJSON(jsonValue));
    }

    /**
     * Get user info
     */
    async getUserInfo(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserOut> {
        const response = await this.getUserInfoRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getUserJoinRequest without sending the request
     */
    async getUserJoinRequestRequestOpts(requestParameters: GetUserJoinRequestRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['joinRequestId'] == null) {
            throw new runtime.RequiredError(
                'joinRequestId',
                'Required parameter "joinRequestId" was null or undefined when calling getUserJoinRequest().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/user/events/join_requests/{join_request_id}`;
        urlPath = urlPath.replace(`{${"join_request_id"}}`, encodeURIComponent(String(requestParameters['joinRequestId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get single join request
     */
    async getUserJoinRequestRaw(requestParameters: GetUserJoinRequestRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<JoinRequestOut>> {
        const requestOptions = await this.getUserJoinRequestRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => JoinRequestOutFromJSON(jsonValue));
    }

    /**
     * Get single join request
     */
    async getUserJoinRequest(requestParameters: GetUserJoinRequestRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<JoinRequestOut> {
        const response = await this.getUserJoinRequestRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getUserJoinRequests without sending the request
     */
    async getUserJoinRequestsRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/user/events/join_requests`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get user join requests
     */
    async getUserJoinRequestsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<JoinRequestOut>>> {
        const requestOptions = await this.getUserJoinRequestsRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(JoinRequestOutFromJSON));
    }

    /**
     * Get user join requests
     */
    async getUserJoinRequests(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<JoinRequestOut>> {
        const response = await this.getUserJoinRequestsRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateUserInfo without sending the request
     */
    async updateUserInfoRequestOpts(requestParameters: UpdateUserInfoOperationRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/user/info`;

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateUserInfoRequestToJSON(requestParameters['updateUserInfoRequest']),
        };
    }

    /**
     * Update user info
     */
    async updateUserInfoRaw(requestParameters: UpdateUserInfoOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserOut>> {
        const requestOptions = await this.updateUserInfoRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserOutFromJSON(jsonValue));
    }

    /**
     * Update user info
     */
    async updateUserInfo(requestParameters: UpdateUserInfoOperationRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserOut> {
        const response = await this.updateUserInfoRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
