"""added status type to join request, added phone to user

Revision ID: 0a9b0aa6510e
Revises: 20250916_sprint4_delta
Create Date: 2025-09-28 21:24:32.519717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import geoalchemy2

# revision identifiers, used by Alembic.
revision: str = '0a9b0aa6510e'
down_revision: Union[str, Sequence[str], None] = '20250916_sprint4_delta'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('spatial_ref_sys')
    op.alter_column('bookings', 'status',
               existing_type=sa.TEXT(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('bookings', 'payment_status',
               existing_type=sa.TEXT(),
               server_default=None,
               existing_nullable=False)
    op.drop_constraint('uq_bookings_timeslot', 'bookings', type_='unique')
    op.alter_column('event_join_requests', 'applicant_email',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('event_join_requests', 'applicant_phone',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('event_join_requests', 'message',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('event_join_requests', 'status',
               existing_type=sa.TEXT(),
               server_default=None,
               existing_nullable=False)
    op.drop_index('ix_event_join_requests_event_status', table_name='event_join_requests')
    op.alter_column('event_participants', 'role',
               existing_type=sa.TEXT(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('event_participants', 'display_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('event_participants', 'email',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('event_participants', 'phone',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index('ix_event_participants_event_id', table_name='event_participants')
    op.drop_constraint('event_participants_join_request_id_fkey', 'event_participants', type_='foreignkey')
    op.create_foreign_key(None, 'event_participants', 'event_join_requests', ['join_request_id'], ['id'])
    op.alter_column('events', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('events', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('events', 'sport_type',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('events', 'city',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('events', 'visibility',
               existing_type=sa.TEXT(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('events', 'invite_token',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('events', 'join_review_required',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('events', 'status',
               existing_type=sa.TEXT(),
               server_default=None,
               existing_nullable=False)
    op.drop_index('ix_events_invite_token_unique', table_name='events', postgresql_where='(invite_token IS NOT NULL)')
    op.drop_index('ix_events_visibility_created', table_name='events')
    op.drop_column('events', 'participants')
    op.add_column('users', sa.Column('phone', sa.String(), nullable=True))
    op.alter_column('users', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('users', 'password_hash',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('users', 'display_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.alter_column('venue_timeslots', 'sport_type',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index('ix_venue_timeslots_venue_time', table_name='venue_timeslots')
    op.drop_constraint('uq_venue_timeslots_unique_window', 'venue_timeslots', type_='unique')
    op.alter_column('venues', 'contact_phone',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('venues', 'partner_code',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index('idx_venues_geo_point', table_name='venues', postgresql_using='gist')
    op.drop_index('ix_venues_city', table_name='venues')
    op.drop_index('ix_venues_geo_point_gist', table_name='venues', postgresql_using='gist')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_venues_geo_point_gist', 'venues', ['geo_point'], unique=False, postgresql_using='gist')
    op.create_index('ix_venues_city', 'venues', ['city'], unique=False)
    op.create_index('idx_venues_geo_point', 'venues', ['geo_point'], unique=False, postgresql_using='gist')
    op.alter_column('venues', 'partner_code',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('venues', 'contact_phone',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('venues', 'geo_point',
               existing_type=sa.Text(),
               type_=geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, from_text='ST_GeogFromText', name='geography'),
               existing_nullable=True)
    op.create_unique_constraint('uq_venue_timeslots_unique_window', 'venue_timeslots', ['venue_id', 'starts_at', 'ends_at'])
    op.create_index('ix_venue_timeslots_venue_time', 'venue_timeslots', ['venue_id', 'starts_at', 'ends_at'], unique=False)
    op.alter_column('venue_timeslots', 'sport_type',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('users', 'display_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=False)
    op.alter_column('users', 'password_hash',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('users', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.drop_column('users', 'phone')
    op.add_column('events', sa.Column('participants', postgresql.ARRAY(sa.UUID()), autoincrement=False, nullable=True))
    op.create_index('ix_events_visibility_created', 'events', ['visibility', 'created_at'], unique=False)
    op.create_index('ix_events_invite_token_unique', 'events', ['invite_token'], unique=True, postgresql_where='(invite_token IS NOT NULL)')
    op.alter_column('events', 'status',
               existing_type=sa.TEXT(),
               server_default=sa.text("'open'::text"),
               existing_nullable=False)
    op.alter_column('events', 'join_review_required',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('events', 'invite_token',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('events', 'visibility',
               existing_type=sa.TEXT(),
               server_default=sa.text("'public'::text"),
               existing_nullable=False)
    op.alter_column('events', 'city',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('events', 'sport_type',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('events', 'description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('events', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.drop_constraint(None, 'event_participants', type_='foreignkey')
    op.create_foreign_key('event_participants_join_request_id_fkey', 'event_participants', 'event_join_requests', ['join_request_id'], ['id'], ondelete='SET NULL')
    op.create_index('ix_event_participants_event_id', 'event_participants', ['event_id'], unique=False)
    op.alter_column('event_participants', 'phone',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('event_participants', 'email',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('event_participants', 'display_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('event_participants', 'role',
               existing_type=sa.TEXT(),
               server_default=sa.text("'member'::text"),
               existing_nullable=False)
    op.create_index('ix_event_join_requests_event_status', 'event_join_requests', ['event_id', 'status'], unique=False)
    op.alter_column('event_join_requests', 'status',
               existing_type=sa.TEXT(),
               server_default=sa.text("'submitted'::text"),
               existing_nullable=False)
    op.alter_column('event_join_requests', 'message',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('event_join_requests', 'applicant_phone',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('event_join_requests', 'applicant_email',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.create_unique_constraint('uq_bookings_timeslot', 'bookings', ['timeslot_id'])
    op.alter_column('bookings', 'payment_status',
               existing_type=sa.TEXT(),
               server_default=sa.text("'none'::text"),
               existing_nullable=False)
    op.alter_column('bookings', 'status',
               existing_type=sa.TEXT(),
               server_default=sa.text("'pending'::text"),
               existing_nullable=False)
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('srid > 0 AND srid <= 998999', name='spatial_ref_sys_srid_check'),
    sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    )
    # ### end Alembic commands ###
