"""refine venue model

Revision ID: 367fd3366847
Revises: 0a9b0aa6510e
Create Date: 2025-09-29 03:33:57.395002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '367fd3366847'
down_revision: Union[str, Sequence[str], None] = '0a9b0aa6510e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:

    # 允許在 GiST 上使用 btree 型別（含 uuid 的等號）
    op.execute('CREATE EXTENSION IF NOT EXISTS "btree_gist";')

    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('venue_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('venue_id', 'name', name='uq_courts_venue_name')
    )
    op.create_index('ix_courts_venue_id', 'courts', ['venue_id'], unique=False)
    op.create_table('court_sport_types',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('court_id', sa.UUID(), nullable=False),
    sa.Column('sport_type', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['court_id'], ['courts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_court_sport_types_court_id', 'court_sport_types', ['court_id'], unique=False)
    op.create_table('court_timeslots',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('court_id', sa.UUID(), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('price_cents', sa.Integer(), nullable=True),
    sa.Column('currency', sa.Text(), server_default=sa.text("'USD'"), nullable=False),
    sa.Column('is_bookable', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    postgresql.ExcludeConstraint((sa.column('court_id'), '='), (sa.text('tstzrange(starts_at, ends_at)'), '&&'), using='gist', name='ex_court_timeslots_overlap'),
    sa.CheckConstraint('(price_cents IS NULL) OR (price_cents >= 0)', name='ck_court_timeslot_price_non_negative'),
    sa.CheckConstraint('char_length(currency) = 3 AND upper(currency) = currency', name='ck_court_timeslot_currency_iso3'),
    sa.CheckConstraint('ends_at > starts_at', name='ck_court_timeslot_valid_range'),
    sa.ForeignKeyConstraint(['court_id'], ['courts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_court_timeslots_court_starts_at', 'court_timeslots', ['court_id', 'starts_at'], unique=False)
    op.create_index('ix_court_timeslots_period_gist', 'court_timeslots', [sa.text('tstzrange(starts_at, ends_at)')], unique=False, postgresql_using='gist')
    op.create_index('ix_venue_timeslots_period_gist', 'venue_timeslots', [sa.text('tstzrange(starts_at, ends_at)')], unique=False, postgresql_using='gist')
    op.create_index('ix_venue_timeslots_venue_starts_at', 'venue_timeslots', ['venue_id', 'starts_at'], unique=False)
    op.drop_column('venue_timeslots', 'sport_type')
    op.alter_column('venues', 'contact_phone',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('venues', 'partner_code',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.create_index('idx_venues_geo_point', 'venues', ['geo_point'], unique=False, postgresql_using='gist')
    op.create_index('ix_venues_city', 'venues', ['city'], unique=False)
    op.create_index('ix_venues_geo_gist', 'venues', ['geo_point'], unique=False, postgresql_using='gist')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_venues_geo_gist', table_name='venues', postgresql_using='gist')
    op.drop_index('ix_venues_city', table_name='venues')
    op.drop_index('idx_venues_geo_point', table_name='venues', postgresql_using='gist')
    op.alter_column('venues', 'partner_code',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('venues', 'contact_phone',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.add_column('venue_timeslots', sa.Column('sport_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index('ix_venue_timeslots_venue_starts_at', table_name='venue_timeslots')
    op.drop_index('ix_venue_timeslots_period_gist', table_name='venue_timeslots', postgresql_using='gist')
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('srid > 0 AND srid <= 998999', name='spatial_ref_sys_srid_check'),
    sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    )
    op.drop_index('ix_court_timeslots_period_gist', table_name='court_timeslots', postgresql_using='gist')
    op.drop_index('ix_court_timeslots_court_starts_at', table_name='court_timeslots')
    op.drop_table('court_timeslots')
    op.drop_index('ix_court_sport_types_court_id', table_name='court_sport_types')
    op.drop_table('court_sport_types')
    op.drop_index('ix_courts_venue_id', table_name='courts')
    op.drop_table('courts')
    # ### end Alembic commands ###
