"""Add amount_due and payment_status to event_participants

Revision ID: 475f921684dc
Revises: 577b208b38a5
Create Date: 2026-03-11 15:33:23.178712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '475f921684dc'
down_revision: Union[str, Sequence[str], None] = '577b208b38a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('event_participants', sa.Column('amount_due', sa.Integer(), server_default='0', nullable=False))
    op.add_column('event_participants', sa.Column('payment_status', sa.Text(), server_default='unpaid', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event_participants', 'payment_status')
    op.drop_column('event_participants', 'amount_due')
    # ### end Alembic commands ###
