"""Add profile preferences to User

Revision ID: 59ea95098cfa
Revises: de91891890da
Create Date: 2026-03-07 17:49:58.455452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '59ea95098cfa'
down_revision: Union[str, Sequence[str], None] = 'de91891890da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('preferred_sports', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('users', sa.Column('skill_levels', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('users', sa.Column('preferred_time_slots', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'preferred_time_slots')
    op.drop_column('users', 'skill_levels')
    op.drop_column('users', 'preferred_sports')
    # ### end Alembic commands ###
