"""Add LineBotConfig model

Revision ID: 759a550414b2
Revises: c3f6b0b60d21
Create Date: 2026-03-15 13:14:13.737996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '759a550414b2'
down_revision: Union[str, Sequence[str], None] = 'c3f6b0b60d21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('line_bot_configs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('bot_id', sa.String(), nullable=False),
    sa.Column('channel_secret', sa.String(), nullable=False),
    sa.Column('channel_access_token', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_line_bot_configs_bot_id'), 'line_bot_configs', ['bot_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_line_bot_configs_bot_id'), table_name='line_bot_configs')
    op.drop_table('line_bot_configs')
    # ### end Alembic commands ###
