"""Add preferred_language and custom_preferences to User

Revision ID: 7d1b1429543f
Revises: 59ea95098cfa
Create Date: 2026-03-07 19:05:17.580458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d1b1429543f'
down_revision: Union[str, Sequence[str], None] = '59ea95098cfa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('preferred_language', sa.String(), nullable=True))
    op.add_column('users', sa.Column('custom_preferences', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'custom_preferences')
    op.drop_column('users', 'preferred_language')
    # ### end Alembic commands ###
