"""initial_schema

Revision ID: de91891890da
Revises: 
Create Date: 2026-03-07 06:22:57.405021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import geoalchemy2

# revision identifiers, used by Alembic.
revision: str = 'de91891890da'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('venues',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('city', sa.Text(), nullable=True),
    sa.Column('geo_point', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, from_text='ST_GeogFromText', name='geography'), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('contact_phone', sa.Text(), nullable=True),
    sa.Column('partner_code', sa.Text(), nullable=True),
    sa.Column('management_type', sa.Text(), nullable=False),
    sa.Column('external_booking_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_venues_city', 'venues', ['city'], unique=False)
    op.create_index('ix_venues_geo_gist', 'venues', ['geo_point'], unique=False, postgresql_using='gist')
    op.create_table('courts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('venue_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('sport_type', sa.Text(), nullable=True),
    sa.Column('environment', sa.Text(), nullable=False),
    sa.Column('surface_type', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('venue_id', 'name', name='uq_courts_venue_name')
    )
    op.create_index('ix_courts_venue_id', 'courts', ['venue_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('related_event_ids', postgresql.ARRAY(sa.UUID()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tickets',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('sport_type', sa.Text(), nullable=False),
    sa.Column('intensity', sa.Text(), nullable=False),
    sa.Column('venue_ids', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.Column('price_min', sa.Integer(), nullable=True),
    sa.Column('price_max', sa.Integer(), nullable=True),
    sa.Column('currency', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('events',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('owner_user_id', sa.UUID(), nullable=False),
    sa.Column('image', sa.Text(), nullable=True),
    sa.Column('venue_id', sa.UUID(), nullable=True),
    sa.Column('court_id', sa.UUID(), nullable=True),
    sa.Column('max_participants', sa.Integer(), nullable=False),
    sa.Column('visibility', sa.Text(), nullable=False),
    sa.Column('invite_token', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('duration_type', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.CheckConstraint("status IN ('open', 'closed')", name='ck_event_status'),
    sa.CheckConstraint("visibility IN ('public', 'private')", name='ck_event_visibility'),
    sa.CheckConstraint('max_participants > 0', name='ck_event_max_gte_min'),
    sa.ForeignKeyConstraint(['court_id'], ['courts.id'], ),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invite_token')
    )
    op.create_index('ix_events_invite_token', 'events', ['invite_token'], unique=False)
    op.create_index('ix_events_owner_status', 'events', ['owner_user_id', 'status'], unique=False)
    op.create_index('ix_events_visibility', 'events', ['visibility'], unique=False)
    op.create_table('time_slots',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('court_id', sa.UUID(), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('price_cents', sa.Integer(), nullable=True),
    sa.Column('currency', sa.Text(), server_default=sa.text("'USD'"), nullable=False),
    sa.Column('is_bookable', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    postgresql.ExcludeConstraint((sa.text('CAST(court_id AS TEXT)'), '='), (sa.text('tstzrange(starts_at, ends_at)'), '&&'), using='gist', name='ex_time_slots_overlap'),
    sa.CheckConstraint('(price_cents IS NULL) OR (price_cents >= 0)', name='ck_time_slot_price_non_negative'),
    sa.CheckConstraint('char_length(currency) = 3 AND upper(currency) = currency', name='ck_time_slot_currency_iso3'),
    sa.CheckConstraint('ends_at > starts_at', name='ck_time_slot_valid_range'),
    sa.ForeignKeyConstraint(['court_id'], ['courts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_time_slots_court_starts_at', 'time_slots', ['court_id', 'starts_at'], unique=False)
    op.create_index('ix_time_slots_period_gist', 'time_slots', [sa.text('tstzrange(starts_at, ends_at)')], unique=False, postgresql_using='gist')
    op.create_table('bookings',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('owner_user_id', sa.UUID(), nullable=False),
    sa.Column('time_slot_id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('payment_status', sa.Text(), nullable=False),
    sa.Column('amount_paid', sa.Integer(), nullable=True),
    sa.Column('currency', sa.Text(), server_default=sa.text("'USD'"), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['time_slot_id'], ['time_slots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event_join_requests',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('applicant_user_id', sa.UUID(), nullable=True),
    sa.Column('applicant_name', sa.Text(), nullable=False),
    sa.Column('applicant_email', sa.String(), nullable=True),
    sa.Column('applicant_phone', sa.String(), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('submitted', 'approved', 'rejected')", name='ck_event_join_requests_status'),
    sa.ForeignKeyConstraint(['applicant_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_event_join_requests_applicant', 'event_join_requests', ['applicant_user_id'], unique=False)
    op.create_index('ix_event_join_requests_event_status', 'event_join_requests', ['event_id', 'status'], unique=False)
    op.create_table('event_participants',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('join_request_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('owner', 'member')", name='ck_event_participants_role'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['join_request_id'], ['event_join_requests.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_event_participants_event', 'event_participants', ['event_id'], unique=False)
    op.create_index('ix_event_participants_user', 'event_participants', ['user_id'], unique=False)
    op.create_index('uq_event_participants_owner', 'event_participants', ['event_id'], unique=True, postgresql_where=sa.text("role = 'owner'"))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('srid > 0 AND srid <= 998999', name='spatial_ref_sys_srid_check'),
    sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    )
    op.drop_index('uq_event_participants_owner', table_name='event_participants', postgresql_where=sa.text("role = 'owner'"))
    op.drop_index('ix_event_participants_user', table_name='event_participants')
    op.drop_index('ix_event_participants_event', table_name='event_participants')
    op.drop_table('event_participants')
    op.drop_index('ix_event_join_requests_event_status', table_name='event_join_requests')
    op.drop_index('ix_event_join_requests_applicant', table_name='event_join_requests')
    op.drop_table('event_join_requests')
    op.drop_table('bookings')
    op.drop_index('ix_time_slots_period_gist', table_name='time_slots', postgresql_using='gist')
    op.drop_index('ix_time_slots_court_starts_at', table_name='time_slots')
    op.drop_table('time_slots')
    op.drop_index('ix_events_visibility', table_name='events')
    op.drop_index('ix_events_owner_status', table_name='events')
    op.drop_index('ix_events_invite_token', table_name='events')
    op.drop_table('events')
    op.drop_table('tickets')
    op.drop_table('notifications')
    op.drop_index('ix_courts_venue_id', table_name='courts')
    op.drop_table('courts')
    op.drop_index('ix_venues_geo_gist', table_name='venues', postgresql_using='gist')
    op.drop_index('ix_venues_city', table_name='venues')
    op.drop_index('idx_venues_geo_point', table_name='venues', postgresql_using='gist')
    op.drop_table('venues')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
