"""initial_migration

Revision ID: faf73b46e241
Revises: 
Create Date: 2025-10-19 11:18:18.989339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import geoalchemy2

# revision identifiers, used by Alembic.
revision: str = 'faf73b46e241'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Enable PostGIS extension for geography support
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis")
    # Enable btree_gist extension for EXCLUDE constraints with UUID
    op.execute("CREATE EXTENSION IF NOT EXISTS btree_gist")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('venues',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('city', sa.Text(), nullable=True),
    sa.Column('geo_point', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, from_text='ST_GeogFromText', name='geography'), nullable=True),
    sa.Column('contact_phone', sa.Text(), nullable=True),
    sa.Column('partner_code', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.Index('ix_venues_city', 'city'),
    sa.Index('ix_venues_geo_gist', 'geo_point', postgresql_using='gist')
    )
    op.create_table('courts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('venue_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('sport_type', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('venue_id', 'name', name='uq_courts_venue_name')
    )
    op.create_index('ix_courts_venue_id', 'courts', ['venue_id'], unique=False)
    op.create_table('teamups',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('owner_user_id', sa.UUID(), nullable=False),
    sa.Column('max_participants', sa.Integer(), nullable=False),
    sa.Column('visibility', sa.Text(), nullable=False),
    sa.Column('invite_token', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('durantion_type', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.CheckConstraint("status IN ('open', 'closed')", name='ck_teamup_status'),
    sa.CheckConstraint("visibility IN ('public', 'private')", name='ck_teamup_visibility'),
    sa.CheckConstraint('max_participants > 0', name='ck_teamup_max_gte_min'),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invite_token')
    )
    op.create_index('ix_teamups_invite_token', 'teamups', ['invite_token'], unique=False)
    op.create_index('ix_teamups_owner_status', 'teamups', ['owner_user_id', 'status'], unique=False)
    op.create_index('ix_teamups_visibility', 'teamups', ['visibility'], unique=False)
    op.create_table('teamup_join_requests',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('teamup_id', sa.UUID(), nullable=False),
    sa.Column('applicant_user_id', sa.UUID(), nullable=True),
    sa.Column('applicant_name', sa.Text(), nullable=False),
    sa.Column('applicant_email', sa.String(), nullable=True),
    sa.Column('applicant_phone', sa.String(), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('submitted', 'approved', 'rejected')", name='ck_teamup_join_requests_status'),
    sa.ForeignKeyConstraint(['applicant_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['teamup_id'], ['teamups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_teamup_join_requests_applicant', 'teamup_join_requests', ['applicant_user_id'], unique=False)
    op.create_index('ix_teamup_join_requests_teamup_status', 'teamup_join_requests', ['teamup_id', 'status'], unique=False)
    op.create_table('timeslots',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('court_id', sa.UUID(), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('price_cents', sa.Integer(), nullable=True),
    sa.Column('currency', sa.Text(), server_default=sa.text("'USD'"), nullable=False),
    sa.Column('is_bookable', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    postgresql.ExcludeConstraint((sa.column('court_id'), '='), (sa.text('tstzrange(starts_at, ends_at)'), '&&'), using='gist', name='ex_timeslots_overlap'),
    sa.CheckConstraint('(price_cents IS NULL) OR (price_cents >= 0)', name='ck_timeslot_price_non_negative'),
    sa.CheckConstraint('char_length(currency) = 3 AND upper(currency) = currency', name='ck_timeslot_currency_iso3'),
    sa.CheckConstraint('ends_at > starts_at', name='ck_timeslot_valid_range'),
    sa.ForeignKeyConstraint(['court_id'], ['courts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_timeslots_court_starts_at', 'timeslots', ['court_id', 'starts_at'], unique=False)
    op.create_index('ix_timeslots_period_gist', 'timeslots', [sa.text('tstzrange(starts_at, ends_at)')], unique=False, postgresql_using='gist')
    op.create_table('bookings',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('owner_user_id', sa.UUID(), nullable=False),
    sa.Column('timeslot_id', sa.UUID(), nullable=False),
    sa.Column('teamup_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('payment_status', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['teamup_id'], ['teamups.id'], ),
    sa.ForeignKeyConstraint(['timeslot_id'], ['timeslots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teamup_participants',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('teamup_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('join_request_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('owner', 'member')", name='ck_teamup_participants_role'),
    sa.ForeignKeyConstraint(['join_request_id'], ['teamup_join_requests.id'], ),
    sa.ForeignKeyConstraint(['teamup_id'], ['teamups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_teamup_participants_teamup', 'teamup_participants', ['teamup_id'], unique=False)
    op.create_index('ix_teamup_participants_user', 'teamup_participants', ['user_id'], unique=False)
    op.create_index('uq_teamup_participants_owner', 'teamup_participants', ['teamup_id'], unique=True, postgresql_where=sa.text("role = 'owner'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_teamup_participants_owner', table_name='teamup_participants', postgresql_where=sa.text("role = 'owner'"))
    op.drop_index('ix_teamup_participants_user', table_name='teamup_participants')
    op.drop_index('ix_teamup_participants_teamup', table_name='teamup_participants')
    op.drop_table('teamup_participants')
    op.drop_table('bookings')
    op.drop_index('ix_timeslots_period_gist', table_name='timeslots', postgresql_using='gist')
    op.drop_index('ix_timeslots_court_starts_at', table_name='timeslots')
    op.drop_table('timeslots')
    op.drop_index('ix_teamup_join_requests_teamup_status', table_name='teamup_join_requests')
    op.drop_index('ix_teamup_join_requests_applicant', table_name='teamup_join_requests')
    op.drop_table('teamup_join_requests')
    op.drop_index('ix_teamups_visibility', table_name='teamups')
    op.drop_index('ix_teamups_owner_status', table_name='teamups')
    op.drop_index('ix_teamups_invite_token', table_name='teamups')
    op.drop_table('teamups')
    op.drop_index('ix_courts_venue_id', table_name='courts')
    op.drop_table('courts')
    op.drop_table('venues')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
