/* tslint:disable */
/* eslint-disable */
/**
 * TeamUp API
 * Sports venue booking and team formation API  Features: - Venue search with geolocation - Timeslot booking - TeamUp creation and management - Join request workflow 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  DeleteAccount200Response,
  TicketCreateIn,
  TicketDetailOut,
  TicketOut,
  TicketUpdateIn,
} from '../models/index';
import {
    DeleteAccount200ResponseFromJSON,
    DeleteAccount200ResponseToJSON,
    TicketCreateInFromJSON,
    TicketCreateInToJSON,
    TicketDetailOutFromJSON,
    TicketDetailOutToJSON,
    TicketOutFromJSON,
    TicketOutToJSON,
    TicketUpdateInFromJSON,
    TicketUpdateInToJSON,
} from '../models/index';

export interface CreateTicketRequest {
    ticketCreateIn: TicketCreateIn;
}

export interface DeleteTicketRequest {
    ticketId: string;
}

export interface GetTicketRequest {
    ticketId: string;
}

export interface UpdateTicketRequest {
    ticketId: string;
    ticketUpdateIn: TicketUpdateIn;
}

/**
 * 
 */
export class TicketsApi extends runtime.BaseAPI {

    /**
     * Creates request options for createTicket without sending the request
     */
    async createTicketRequestOpts(requestParameters: CreateTicketRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['ticketCreateIn'] == null) {
            throw new runtime.RequiredError(
                'ticketCreateIn',
                'Required parameter "ticketCreateIn" was null or undefined when calling createTicket().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/tickets`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: TicketCreateInToJSON(requestParameters['ticketCreateIn']),
        };
    }

    /**
     * Create a new ticket
     */
    async createTicketRaw(requestParameters: CreateTicketRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TicketOut>> {
        const requestOptions = await this.createTicketRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TicketOutFromJSON(jsonValue));
    }

    /**
     * Create a new ticket
     */
    async createTicket(requestParameters: CreateTicketRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TicketOut> {
        const response = await this.createTicketRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deleteTicket without sending the request
     */
    async deleteTicketRequestOpts(requestParameters: DeleteTicketRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['ticketId'] == null) {
            throw new runtime.RequiredError(
                'ticketId',
                'Required parameter "ticketId" was null or undefined when calling deleteTicket().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/tickets/{ticket_id}`;
        urlPath = urlPath.replace(`{${"ticket_id"}}`, encodeURIComponent(String(requestParameters['ticketId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Delete ticket
     */
    async deleteTicketRaw(requestParameters: DeleteTicketRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DeleteAccount200Response>> {
        const requestOptions = await this.deleteTicketRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DeleteAccount200ResponseFromJSON(jsonValue));
    }

    /**
     * Delete ticket
     */
    async deleteTicket(requestParameters: DeleteTicketRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DeleteAccount200Response> {
        const response = await this.deleteTicketRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getTicket without sending the request
     */
    async getTicketRequestOpts(requestParameters: GetTicketRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['ticketId'] == null) {
            throw new runtime.RequiredError(
                'ticketId',
                'Required parameter "ticketId" was null or undefined when calling getTicket().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/tickets/{ticket_id}`;
        urlPath = urlPath.replace(`{${"ticket_id"}}`, encodeURIComponent(String(requestParameters['ticketId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get ticket details with matched events
     */
    async getTicketRaw(requestParameters: GetTicketRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TicketDetailOut>> {
        const requestOptions = await this.getTicketRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TicketDetailOutFromJSON(jsonValue));
    }

    /**
     * Get ticket details with matched events
     */
    async getTicket(requestParameters: GetTicketRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TicketDetailOut> {
        const response = await this.getTicketRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listTickets without sending the request
     */
    async listTicketsRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/tickets`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List user\'s tickets
     */
    async listTicketsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<TicketOut>>> {
        const requestOptions = await this.listTicketsRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(TicketOutFromJSON));
    }

    /**
     * List user\'s tickets
     */
    async listTickets(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<TicketOut>> {
        const response = await this.listTicketsRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateTicket without sending the request
     */
    async updateTicketRequestOpts(requestParameters: UpdateTicketRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['ticketId'] == null) {
            throw new runtime.RequiredError(
                'ticketId',
                'Required parameter "ticketId" was null or undefined when calling updateTicket().'
            );
        }

        if (requestParameters['ticketUpdateIn'] == null) {
            throw new runtime.RequiredError(
                'ticketUpdateIn',
                'Required parameter "ticketUpdateIn" was null or undefined when calling updateTicket().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/tickets/{ticket_id}`;
        urlPath = urlPath.replace(`{${"ticket_id"}}`, encodeURIComponent(String(requestParameters['ticketId'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: TicketUpdateInToJSON(requestParameters['ticketUpdateIn']),
        };
    }

    /**
     * Update ticket
     */
    async updateTicketRaw(requestParameters: UpdateTicketRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TicketDetailOut>> {
        const requestOptions = await this.updateTicketRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TicketDetailOutFromJSON(jsonValue));
    }

    /**
     * Update ticket
     */
    async updateTicket(requestParameters: UpdateTicketRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TicketDetailOut> {
        const response = await this.updateTicketRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
