/* tslint:disable */
/* eslint-disable */
/**
 * TeamUp API
 * Sports venue booking and team formation API  Features: - Venue search with geolocation - Timeslot booking - TeamUp creation and management - Join request workflow 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CourtOut,
  CourtUpdateIn,
  DeleteAccount200Response,
  TimeSlotCreateIn,
  TimeSlotOut,
  TimeSlotUpdateIn,
  VenueCreateIn,
  VenueDetail,
  VenueSearchResult,
  VenueUpdateIn,
} from '../models/index';
import {
    CourtOutFromJSON,
    CourtOutToJSON,
    CourtUpdateInFromJSON,
    CourtUpdateInToJSON,
    DeleteAccount200ResponseFromJSON,
    DeleteAccount200ResponseToJSON,
    TimeSlotCreateInFromJSON,
    TimeSlotCreateInToJSON,
    TimeSlotOutFromJSON,
    TimeSlotOutToJSON,
    TimeSlotUpdateInFromJSON,
    TimeSlotUpdateInToJSON,
    VenueCreateInFromJSON,
    VenueCreateInToJSON,
    VenueDetailFromJSON,
    VenueDetailToJSON,
    VenueSearchResultFromJSON,
    VenueSearchResultToJSON,
    VenueUpdateInFromJSON,
    VenueUpdateInToJSON,
} from '../models/index';

export interface CreateTimeSlotRequest {
    venueId: string;
    courtId: string;
    timeSlotCreateIn: TimeSlotCreateIn;
}

export interface CreateVenueRequest {
    venueCreateIn: VenueCreateIn;
}

export interface DeleteCourtRequest {
    venueId: string;
    courtId: string;
}

export interface DeleteTimeSlotRequest {
    venueId: string;
    courtId: string;
    timeSlotId: string;
}

export interface DeleteVenueRequest {
    venueId: string;
}

export interface GetCourtRequest {
    venueId: string;
    courtId: string;
}

export interface GetCourtTimeSlotsRequest {
    venueId: string;
    courtId: string;
    date?: Date;
}

export interface GetTimeSlotRequest {
    venueId: string;
    courtId: string;
    timeSlotId: string;
}

export interface GetVenueByIdRequest {
    venueId: string;
}

export interface SearchVenuesRequest {
    lat?: number;
    lng?: number;
    distance?: number;
    datetime?: string;
    sportType?: string;
}

export interface UpdateCourtRequest {
    venueId: string;
    courtId: string;
    courtUpdateIn: CourtUpdateIn;
}

export interface UpdateTimeSlotRequest {
    venueId: string;
    courtId: string;
    timeSlotId: string;
    timeSlotUpdateIn: TimeSlotUpdateIn;
}

export interface UpdateVenueRequest {
    venueId: string;
    venueUpdateIn: VenueUpdateIn;
}

/**
 * 
 */
export class VenuesApi extends runtime.BaseAPI {

    /**
     * Creates request options for createTimeSlot without sending the request
     */
    async createTimeSlotRequestOpts(requestParameters: CreateTimeSlotRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['venueId'] == null) {
            throw new runtime.RequiredError(
                'venueId',
                'Required parameter "venueId" was null or undefined when calling createTimeSlot().'
            );
        }

        if (requestParameters['courtId'] == null) {
            throw new runtime.RequiredError(
                'courtId',
                'Required parameter "courtId" was null or undefined when calling createTimeSlot().'
            );
        }

        if (requestParameters['timeSlotCreateIn'] == null) {
            throw new runtime.RequiredError(
                'timeSlotCreateIn',
                'Required parameter "timeSlotCreateIn" was null or undefined when calling createTimeSlot().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/venues/{venue_id}/courts/{court_id}/time_slots`;
        urlPath = urlPath.replace(`{${"venue_id"}}`, encodeURIComponent(String(requestParameters['venueId'])));
        urlPath = urlPath.replace(`{${"court_id"}}`, encodeURIComponent(String(requestParameters['courtId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: TimeSlotCreateInToJSON(requestParameters['timeSlotCreateIn']),
        };
    }

    /**
     * Create new timeslot(s)
     */
    async createTimeSlotRaw(requestParameters: CreateTimeSlotRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TimeSlotOut>> {
        const requestOptions = await this.createTimeSlotRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TimeSlotOutFromJSON(jsonValue));
    }

    /**
     * Create new timeslot(s)
     */
    async createTimeSlot(requestParameters: CreateTimeSlotRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TimeSlotOut> {
        const response = await this.createTimeSlotRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for createVenue without sending the request
     */
    async createVenueRequestOpts(requestParameters: CreateVenueRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['venueCreateIn'] == null) {
            throw new runtime.RequiredError(
                'venueCreateIn',
                'Required parameter "venueCreateIn" was null or undefined when calling createVenue().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/venues`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: VenueCreateInToJSON(requestParameters['venueCreateIn']),
        };
    }

    /**
     * Create venue
     */
    async createVenueRaw(requestParameters: CreateVenueRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<VenueDetail>> {
        const requestOptions = await this.createVenueRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => VenueDetailFromJSON(jsonValue));
    }

    /**
     * Create venue
     */
    async createVenue(requestParameters: CreateVenueRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<VenueDetail> {
        const response = await this.createVenueRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deleteCourt without sending the request
     */
    async deleteCourtRequestOpts(requestParameters: DeleteCourtRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['venueId'] == null) {
            throw new runtime.RequiredError(
                'venueId',
                'Required parameter "venueId" was null or undefined when calling deleteCourt().'
            );
        }

        if (requestParameters['courtId'] == null) {
            throw new runtime.RequiredError(
                'courtId',
                'Required parameter "courtId" was null or undefined when calling deleteCourt().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/venues/{venue_id}/courts/{court_id}`;
        urlPath = urlPath.replace(`{${"venue_id"}}`, encodeURIComponent(String(requestParameters['venueId'])));
        urlPath = urlPath.replace(`{${"court_id"}}`, encodeURIComponent(String(requestParameters['courtId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Delete court
     */
    async deleteCourtRaw(requestParameters: DeleteCourtRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DeleteAccount200Response>> {
        const requestOptions = await this.deleteCourtRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DeleteAccount200ResponseFromJSON(jsonValue));
    }

    /**
     * Delete court
     */
    async deleteCourt(requestParameters: DeleteCourtRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DeleteAccount200Response> {
        const response = await this.deleteCourtRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deleteTimeSlot without sending the request
     */
    async deleteTimeSlotRequestOpts(requestParameters: DeleteTimeSlotRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['venueId'] == null) {
            throw new runtime.RequiredError(
                'venueId',
                'Required parameter "venueId" was null or undefined when calling deleteTimeSlot().'
            );
        }

        if (requestParameters['courtId'] == null) {
            throw new runtime.RequiredError(
                'courtId',
                'Required parameter "courtId" was null or undefined when calling deleteTimeSlot().'
            );
        }

        if (requestParameters['timeSlotId'] == null) {
            throw new runtime.RequiredError(
                'timeSlotId',
                'Required parameter "timeSlotId" was null or undefined when calling deleteTimeSlot().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/venues/{venue_id}/courts/{court_id}/time_slots/{time_slot_id}`;
        urlPath = urlPath.replace(`{${"venue_id"}}`, encodeURIComponent(String(requestParameters['venueId'])));
        urlPath = urlPath.replace(`{${"court_id"}}`, encodeURIComponent(String(requestParameters['courtId'])));
        urlPath = urlPath.replace(`{${"time_slot_id"}}`, encodeURIComponent(String(requestParameters['timeSlotId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Delete timeslot
     */
    async deleteTimeSlotRaw(requestParameters: DeleteTimeSlotRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DeleteAccount200Response>> {
        const requestOptions = await this.deleteTimeSlotRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DeleteAccount200ResponseFromJSON(jsonValue));
    }

    /**
     * Delete timeslot
     */
    async deleteTimeSlot(requestParameters: DeleteTimeSlotRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DeleteAccount200Response> {
        const response = await this.deleteTimeSlotRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deleteVenue without sending the request
     */
    async deleteVenueRequestOpts(requestParameters: DeleteVenueRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['venueId'] == null) {
            throw new runtime.RequiredError(
                'venueId',
                'Required parameter "venueId" was null or undefined when calling deleteVenue().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/venues/{venue_id}`;
        urlPath = urlPath.replace(`{${"venue_id"}}`, encodeURIComponent(String(requestParameters['venueId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Delete venue
     */
    async deleteVenueRaw(requestParameters: DeleteVenueRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DeleteAccount200Response>> {
        const requestOptions = await this.deleteVenueRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DeleteAccount200ResponseFromJSON(jsonValue));
    }

    /**
     * Delete venue
     */
    async deleteVenue(requestParameters: DeleteVenueRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DeleteAccount200Response> {
        const response = await this.deleteVenueRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getCourt without sending the request
     */
    async getCourtRequestOpts(requestParameters: GetCourtRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['venueId'] == null) {
            throw new runtime.RequiredError(
                'venueId',
                'Required parameter "venueId" was null or undefined when calling getCourt().'
            );
        }

        if (requestParameters['courtId'] == null) {
            throw new runtime.RequiredError(
                'courtId',
                'Required parameter "courtId" was null or undefined when calling getCourt().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/venues/{venue_id}/courts/{court_id}`;
        urlPath = urlPath.replace(`{${"venue_id"}}`, encodeURIComponent(String(requestParameters['venueId'])));
        urlPath = urlPath.replace(`{${"court_id"}}`, encodeURIComponent(String(requestParameters['courtId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get court detail
     */
    async getCourtRaw(requestParameters: GetCourtRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CourtOut>> {
        const requestOptions = await this.getCourtRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CourtOutFromJSON(jsonValue));
    }

    /**
     * Get court detail
     */
    async getCourt(requestParameters: GetCourtRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CourtOut> {
        const response = await this.getCourtRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getCourtTimeSlots without sending the request
     */
    async getCourtTimeSlotsRequestOpts(requestParameters: GetCourtTimeSlotsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['venueId'] == null) {
            throw new runtime.RequiredError(
                'venueId',
                'Required parameter "venueId" was null or undefined when calling getCourtTimeSlots().'
            );
        }

        if (requestParameters['courtId'] == null) {
            throw new runtime.RequiredError(
                'courtId',
                'Required parameter "courtId" was null or undefined when calling getCourtTimeSlots().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['date'] != null) {
            queryParameters['date'] = (requestParameters['date'] as any).toISOString().substring(0,10);
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/venues/{venue_id}/courts/{court_id}/time_slots`;
        urlPath = urlPath.replace(`{${"venue_id"}}`, encodeURIComponent(String(requestParameters['venueId'])));
        urlPath = urlPath.replace(`{${"court_id"}}`, encodeURIComponent(String(requestParameters['courtId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get available time slots for a court
     */
    async getCourtTimeSlotsRaw(requestParameters: GetCourtTimeSlotsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<TimeSlotOut>>> {
        const requestOptions = await this.getCourtTimeSlotsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(TimeSlotOutFromJSON));
    }

    /**
     * Get available time slots for a court
     */
    async getCourtTimeSlots(requestParameters: GetCourtTimeSlotsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<TimeSlotOut>> {
        const response = await this.getCourtTimeSlotsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getTimeSlot without sending the request
     */
    async getTimeSlotRequestOpts(requestParameters: GetTimeSlotRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['venueId'] == null) {
            throw new runtime.RequiredError(
                'venueId',
                'Required parameter "venueId" was null or undefined when calling getTimeSlot().'
            );
        }

        if (requestParameters['courtId'] == null) {
            throw new runtime.RequiredError(
                'courtId',
                'Required parameter "courtId" was null or undefined when calling getTimeSlot().'
            );
        }

        if (requestParameters['timeSlotId'] == null) {
            throw new runtime.RequiredError(
                'timeSlotId',
                'Required parameter "timeSlotId" was null or undefined when calling getTimeSlot().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/venues/{venue_id}/courts/{court_id}/time_slots/{time_slot_id}`;
        urlPath = urlPath.replace(`{${"venue_id"}}`, encodeURIComponent(String(requestParameters['venueId'])));
        urlPath = urlPath.replace(`{${"court_id"}}`, encodeURIComponent(String(requestParameters['courtId'])));
        urlPath = urlPath.replace(`{${"time_slot_id"}}`, encodeURIComponent(String(requestParameters['timeSlotId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get timeslot details
     */
    async getTimeSlotRaw(requestParameters: GetTimeSlotRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TimeSlotOut>> {
        const requestOptions = await this.getTimeSlotRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TimeSlotOutFromJSON(jsonValue));
    }

    /**
     * Get timeslot details
     */
    async getTimeSlot(requestParameters: GetTimeSlotRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TimeSlotOut> {
        const response = await this.getTimeSlotRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getVenueById without sending the request
     */
    async getVenueByIdRequestOpts(requestParameters: GetVenueByIdRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['venueId'] == null) {
            throw new runtime.RequiredError(
                'venueId',
                'Required parameter "venueId" was null or undefined when calling getVenueById().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/venues/{venue_id}`;
        urlPath = urlPath.replace(`{${"venue_id"}}`, encodeURIComponent(String(requestParameters['venueId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get venue details
     */
    async getVenueByIdRaw(requestParameters: GetVenueByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<VenueDetail>> {
        const requestOptions = await this.getVenueByIdRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => VenueDetailFromJSON(jsonValue));
    }

    /**
     * Get venue details
     */
    async getVenueById(requestParameters: GetVenueByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<VenueDetail> {
        const response = await this.getVenueByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for searchVenues without sending the request
     */
    async searchVenuesRequestOpts(requestParameters: SearchVenuesRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['lat'] != null) {
            queryParameters['lat'] = requestParameters['lat'];
        }

        if (requestParameters['lng'] != null) {
            queryParameters['lng'] = requestParameters['lng'];
        }

        if (requestParameters['distance'] != null) {
            queryParameters['distance'] = requestParameters['distance'];
        }

        if (requestParameters['datetime'] != null) {
            queryParameters['datetime'] = requestParameters['datetime'];
        }

        if (requestParameters['sportType'] != null) {
            queryParameters['sport_type'] = requestParameters['sportType'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/venues`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Search venues based on location, datetime, and sport type. Supports geolocation-based search with distance filtering. 
     * Search venues with available time slots
     */
    async searchVenuesRaw(requestParameters: SearchVenuesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<VenueSearchResult>>> {
        const requestOptions = await this.searchVenuesRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(VenueSearchResultFromJSON));
    }

    /**
     * Search venues based on location, datetime, and sport type. Supports geolocation-based search with distance filtering. 
     * Search venues with available time slots
     */
    async searchVenues(requestParameters: SearchVenuesRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<VenueSearchResult>> {
        const response = await this.searchVenuesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateCourt without sending the request
     */
    async updateCourtRequestOpts(requestParameters: UpdateCourtRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['venueId'] == null) {
            throw new runtime.RequiredError(
                'venueId',
                'Required parameter "venueId" was null or undefined when calling updateCourt().'
            );
        }

        if (requestParameters['courtId'] == null) {
            throw new runtime.RequiredError(
                'courtId',
                'Required parameter "courtId" was null or undefined when calling updateCourt().'
            );
        }

        if (requestParameters['courtUpdateIn'] == null) {
            throw new runtime.RequiredError(
                'courtUpdateIn',
                'Required parameter "courtUpdateIn" was null or undefined when calling updateCourt().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/venues/{venue_id}/courts/{court_id}`;
        urlPath = urlPath.replace(`{${"venue_id"}}`, encodeURIComponent(String(requestParameters['venueId'])));
        urlPath = urlPath.replace(`{${"court_id"}}`, encodeURIComponent(String(requestParameters['courtId'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: CourtUpdateInToJSON(requestParameters['courtUpdateIn']),
        };
    }

    /**
     * Update court
     */
    async updateCourtRaw(requestParameters: UpdateCourtRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CourtOut>> {
        const requestOptions = await this.updateCourtRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CourtOutFromJSON(jsonValue));
    }

    /**
     * Update court
     */
    async updateCourt(requestParameters: UpdateCourtRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CourtOut> {
        const response = await this.updateCourtRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateTimeSlot without sending the request
     */
    async updateTimeSlotRequestOpts(requestParameters: UpdateTimeSlotRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['venueId'] == null) {
            throw new runtime.RequiredError(
                'venueId',
                'Required parameter "venueId" was null or undefined when calling updateTimeSlot().'
            );
        }

        if (requestParameters['courtId'] == null) {
            throw new runtime.RequiredError(
                'courtId',
                'Required parameter "courtId" was null or undefined when calling updateTimeSlot().'
            );
        }

        if (requestParameters['timeSlotId'] == null) {
            throw new runtime.RequiredError(
                'timeSlotId',
                'Required parameter "timeSlotId" was null or undefined when calling updateTimeSlot().'
            );
        }

        if (requestParameters['timeSlotUpdateIn'] == null) {
            throw new runtime.RequiredError(
                'timeSlotUpdateIn',
                'Required parameter "timeSlotUpdateIn" was null or undefined when calling updateTimeSlot().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/venues/{venue_id}/courts/{court_id}/time_slots/{time_slot_id}`;
        urlPath = urlPath.replace(`{${"venue_id"}}`, encodeURIComponent(String(requestParameters['venueId'])));
        urlPath = urlPath.replace(`{${"court_id"}}`, encodeURIComponent(String(requestParameters['courtId'])));
        urlPath = urlPath.replace(`{${"time_slot_id"}}`, encodeURIComponent(String(requestParameters['timeSlotId'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: TimeSlotUpdateInToJSON(requestParameters['timeSlotUpdateIn']),
        };
    }

    /**
     * Update timeslot
     */
    async updateTimeSlotRaw(requestParameters: UpdateTimeSlotRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TimeSlotOut>> {
        const requestOptions = await this.updateTimeSlotRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TimeSlotOutFromJSON(jsonValue));
    }

    /**
     * Update timeslot
     */
    async updateTimeSlot(requestParameters: UpdateTimeSlotRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TimeSlotOut> {
        const response = await this.updateTimeSlotRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateVenue without sending the request
     */
    async updateVenueRequestOpts(requestParameters: UpdateVenueRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['venueId'] == null) {
            throw new runtime.RequiredError(
                'venueId',
                'Required parameter "venueId" was null or undefined when calling updateVenue().'
            );
        }

        if (requestParameters['venueUpdateIn'] == null) {
            throw new runtime.RequiredError(
                'venueUpdateIn',
                'Required parameter "venueUpdateIn" was null or undefined when calling updateVenue().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/venues/{venue_id}`;
        urlPath = urlPath.replace(`{${"venue_id"}}`, encodeURIComponent(String(requestParameters['venueId'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: VenueUpdateInToJSON(requestParameters['venueUpdateIn']),
        };
    }

    /**
     * Update venue
     */
    async updateVenueRaw(requestParameters: UpdateVenueRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<VenueDetail>> {
        const requestOptions = await this.updateVenueRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => VenueDetailFromJSON(jsonValue));
    }

    /**
     * Update venue
     */
    async updateVenue(requestParameters: UpdateVenueRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<VenueDetail> {
        const response = await this.updateVenueRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
